In [1]:
import numpy as np
import pandas as pd
import geopandas
import shelve

## Data ingestion

In [ ]:
# data_dict = pd.read_excel('data/raw/property_DataDict.xlsx', index_col='Field Name')

In [ ]:
# data = original raw data set
# properties_raw = pd.read_csv('data/raw/allegheny_PropertyAssessments.csv', index_col='PARID')
# properties_raw = pd.read_csv('https://data.wprdc.org/dataset/2b3df818-601e-4f06-b150-643557229491/resource/9a1c60bd-f9f7-4aba-aeb7-af8c3aaa44e5/download/allegheny_county_master_file.csv', 
#                              index_col='PARID')

In [1633]:
# altered dataframe
properties_c = properties_raw.copy()

In [ ]:
select_cols = [
    'PROPERTYHOUSENUM', 'PROPERTYFRACTION', 'PROPERTYUNIT', 'PROPERTYADDRESS', 'PROPERTYCITY', 'PROPERTYSTATE', 'PROPERTYZIP',
    'MUNICODE', 'MUNIDESC', 'NEIGHCODE', 'NEIGHDESC', 'SCHOOLCODE', 'SCHOOLDESC', 'LEGAL1', 'LEGAL2', 'LEGAL3', 
    'TAXCODE', 'TAXDESC', 'TAXSUBCODE', 'TAXSUBCODE_DESC', 'OWNERCODE', 'OWNERDESC', 'CLASS', 'CLASSDESC', 'USECODE', 'USEDESC', 'LOTAREA',
    'SALEDATE', 'SALEPRICE', 'SALECODE', 'SALEDESC', 'PREVSALEDATE', 'PREVSALEPRICE', 'PREVSALEDATE2', 'PREVSALEPRICE2',
    'CHANGENOTICEADDRESS1', 'CHANGENOTICEADDRESS2', 'CHANGENOTICEADDRESS3', 'CHANGENOTICEADDRESS4',
    'COUNTYBUILDING', 'COUNTYLAND', 'COUNTYTOTAL', 'COUNTYEXEMPTBLDG', 'LOCALBUILDING', 'LOCALLAND', 'LOCALTOTAL',
    'FAIRMARKETBUILDING', 'FAIRMARKETLAND', 'FAIRMARKETTOTAL',
    'STYLE', 'STYLEDESC', 'STORIES', 'YEARBLT', 'TOTALROOMS', 'BEDROOMS', 'FULLBATHS', 'HALFBATHS',
    'GRADE', 'GRADEDESC', 'CONDITION', 'CONDITIONDESC', 'CDU', 'CDUDESC',
    'TAXYEAR'
]
properties_c = properties_c[select_cols]

In [1635]:
properties_c.head()

,PROPERTYHOUSENUM,PROPERTYFRACTION,PROPERTYUNIT,PROPERTYADDRESS,PROPERTYCITY,PROPERTYSTATE,PROPERTYZIP,MUNICODE,MUNIDESC,NEIGHCODE,...,BEDROOMS,FULLBATHS,HALFBATHS,GRADE,GRADEDESC,CONDITION,CONDITIONDESC,CDU,CDUDESC,TAXYEAR
PARID,,,,,,,,,,,,,,,,,,,,,
0001C00167000000,444.0,,,LIBERTY AVE,PITTSBURGH,PA,15222.0,101,1st Ward - PITTSBURGH,51C01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026
0001C00200000001,501.0,,,STANWIX ST,PITTSBURGH,PA,15222.0,101,1st Ward - PITTSBURGH,51C01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026
0001C00224000000,500.0,,,LIBERTY AVE,PITTSBURGH,PA,15222.0,101,1st Ward - PITTSBURGH,51C01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026
0001C00228000000,400.0,-424,,STANWIX ST,PITTSBURGH,PA,15222.0,101,1st Ward - PITTSBURGH,51C01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026
0001C00228000100,100.0,,,FORBES AVE,PITTSBURGH,PA,15222.0,101,1st Ward - PITTSBURGH,51C01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026

In [1636]:
properties_c.info()

<class 'pandas.core.frame.DataFrame'>
Index: 584902 entries, 0001C00167000000 to 0185P00088000000
Data columns (total 63 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   PROPERTYHOUSENUM      584897 non-null  float64
 1   PROPERTYFRACTION      584902 non-null  object
 2   PROPERTYUNIT          584902 non-null  object
 3   PROPERTYADDRESS       584902 non-null  object
 4   PROPERTYCITY          584899 non-null  object
 5   PROPERTYSTATE         584902 non-null  object
 6   PROPERTYZIP           584900 non-null  float64
 7   MUNICODE              584902 non-null  int64
 8   MUNIDESC              584902 non-null  object
 9   NEIGHCODE             584902 non-null  object
 10  NEIGHDESC             583995 non-null  object
 11  SCHOOLCODE            584902 non-null  int64
 12  SCHOOLDESC            584902 non-null  object
 13  LEGAL1                584876 non-null  object
 14  LEGAL2                521078 non-null  object
 15  LEGAL3                336373 non-null  object
 16  TAXCODE               584902 non-null  object
 17  TAXDESC               584902 non-null  object
 18  TAXSUBCODE            1711 non-null    object
 19  TAXSUBCODE_DESC       1711 non-null    object
 20  OWNERCODE             584902 non-null  int64
 21  OWNERDESC             584902 non-null  object
 22  CLASS                 584902 non-null  object
 23  USECODE               584902 non-null  int64
 24  USEDESC               584902 non-null  object
 25  LOTAREA               584902 non-null  int64
 26  SALEDATE              578671 non-null  object
 27  SALEPRICE             576152 non-null  float64
 28  SALECODE              577884 non-null  object
 29  SALEDESC              576709 non-null  object
 30  PREVSALEDATE          421445 non-null  object
 31  PREVSALEPRICE         419605 non-null  float64
 32  PREVSALEDATE2         249500 non-null  object
 33  PREVSALEPRICE2        248745 non-null  float64
 34  CHANGENOTICEADDRESS1  584902 non-null  object
 35  CHANGENOTICEADDRESS2  584902 non-null  object
 36  CHANGENOTICEADDRESS3  584902 non-null  object
 37  CHANGENOTICEADDRESS4  572812 non-null  object
 38  COUNTYBUILDING        584902 non-null  int64
 39  COUNTYLAND            584902 non-null  int64
 40  COUNTYTOTAL           584902 non-null  int64
 41  COUNTYEXEMPTBLDG      584902 non-null  int64
 42  LOCALBUILDING         584902 non-null  int64
 43  LOCALLAND             584902 non-null  int64
 44  LOCALTOTAL            584902 non-null  int64
 45  FAIRMARKETBUILDING    584902 non-null  int64
 46  FAIRMARKETLAND        584902 non-null  int64
 47  FAIRMARKETTOTAL       584902 non-null  int64
 48  STYLE                 449180 non-null  object
 49  STYLEDESC             449180 non-null  object
 50  STORIES               449188 non-null  float64
 51  YEARBLT               449203 non-null  float64
 52  TOTALROOMS            449098 non-null  float64
 53  BEDROOMS              449159 non-null  float64
 54  FULLBATHS             449090 non-null  float64
 55  HALFBATHS             444524 non-null  float64
 56  GRADE                 449181 non-null  object
 57  GRADEDESC             449181 non-null  object
 58  CONDITION             449120 non-null  float64
 59  CONDITIONDESC         449120 non-null  object
 60  CDU                   449112 non-null  object
 61  CDUDESC               449112 non-null  object
 62  TAXYEAR               584902 non-null  int64
dtypes: float64(12), int64(16), object(35)
memory usage: 285.6+ MB

In [1637]:
properties_c.isna().sum().sort_values(ascending=False).head(35)

TAXSUBCODE_DESC         583191
TAXSUBCODE              583191
PREVSALEPRICE2          336157
PREVSALEDATE2           335402
LEGAL3                  248529
PREVSALEPRICE           165297
PREVSALEDATE            163457
HALFBATHS               140378
FULLBATHS               135812
TOTALROOMS              135804
CDU                     135790
CDUDESC                 135790
CONDITION               135782
CONDITIONDESC           135782
BEDROOMS                135743
STYLE                   135722
STYLEDESC               135722
GRADE                   135721
GRADEDESC               135721
STORIES                 135714
YEARBLT                 135699
LEGAL2                   63824
CHANGENOTICEADDRESS4     12090
SALEPRICE                 8750
SALEDESC                  8193
SALECODE                  7018
SALEDATE                  6231
NEIGHDESC                  907
LEGAL1                      26
PROPERTYHOUSENUM             5
PROPERTYCITY                 3
PROPERTYZIP                  2
LOTAREA                      0
FAIRMARKETTOTAL              0
PROPERTYUNIT                 0
dtype: int64

## Type correction

In [1638]:
properties_c.info()

<class 'pandas.core.frame.DataFrame'>
Index: 584902 entries, 0001C00167000000 to 0185P00088000000
Data columns (total 63 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   PROPERTYHOUSENUM      584897 non-null  float64
 1   PROPERTYFRACTION      584902 non-null  object
 2   PROPERTYUNIT          584902 non-null  object
 3   PROPERTYADDRESS       584902 non-null  object
 4   PROPERTYCITY          584899 non-null  object
 5   PROPERTYSTATE         584902 non-null  object
 6   PROPERTYZIP           584900 non-null  float64
 7   MUNICODE              584902 non-null  int64
 8   MUNIDESC              584902 non-null  object
 9   NEIGHCODE             584902 non-null  object
 10  NEIGHDESC             583995 non-null  object
 11  SCHOOLCODE            584902 non-null  int64
 12  SCHOOLDESC            584902 non-null  object
 13  LEGAL1                584876 non-null  object
 14  LEGAL2                521078 non-null  object
 15  LEGAL3                336373 non-null  object
 16  TAXCODE               584902 non-null  object
 17  TAXDESC               584902 non-null  object
 18  TAXSUBCODE            1711 non-null    object
 19  TAXSUBCODE_DESC       1711 non-null    object
 20  OWNERCODE             584902 non-null  int64
 21  OWNERDESC             584902 non-null  object
 22  CLASS                 584902 non-null  object
 23  USECODE               584902 non-null  int64
 24  USEDESC               584902 non-null  object
 25  LOTAREA               584902 non-null  int64
 26  SALEDATE              578671 non-null  object
 27  SALEPRICE             576152 non-null  float64
 28  SALECODE              577884 non-null  object
 29  SALEDESC              576709 non-null  object
 30  PREVSALEDATE          421445 non-null  object
 31  PREVSALEPRICE         419605 non-null  float64
 32  PREVSALEDATE2         249500 non-null  object
 33  PREVSALEPRICE2        248745 non-null  float64
 34  CHANGENOTICEADDRESS1  584902 non-null  object
 35  CHANGENOTICEADDRESS2  584902 non-null  object
 36  CHANGENOTICEADDRESS3  584902 non-null  object
 37  CHANGENOTICEADDRESS4  572812 non-null  object
 38  COUNTYBUILDING        584902 non-null  int64
 39  COUNTYLAND            584902 non-null  int64
 40  COUNTYTOTAL           584902 non-null  int64
 41  COUNTYEXEMPTBLDG      584902 non-null  int64
 42  LOCALBUILDING         584902 non-null  int64
 43  LOCALLAND             584902 non-null  int64
 44  LOCALTOTAL            584902 non-null  int64
 45  FAIRMARKETBUILDING    584902 non-null  int64
 46  FAIRMARKETLAND        584902 non-null  int64
 47  FAIRMARKETTOTAL       584902 non-null  int64
 48  STYLE                 449180 non-null  object
 49  STYLEDESC             449180 non-null  object
 50  STORIES               449188 non-null  float64
 51  YEARBLT               449203 non-null  float64
 52  TOTALROOMS            449098 non-null  float64
 53  BEDROOMS              449159 non-null  float64
 54  FULLBATHS             449090 non-null  float64
 55  HALFBATHS             444524 non-null  float64
 56  GRADE                 449181 non-null  object
 57  GRADEDESC             449181 non-null  object
 58  CONDITION             449120 non-null  float64
 59  CONDITIONDESC         449120 non-null  object
 60  CDU                   449112 non-null  object
 61  CDUDESC               449112 non-null  object
 62  TAXYEAR               584902 non-null  int64
dtypes: float64(12), int64(16), object(35)
memory usage: 285.6+ MB

### Integer columns

In [1639]:
# TODO: come back to this one maybe
properties_c['CHANGENOTICEADDRESS4'].value_counts()

CHANGENOTICEADDRESS4
15219.0    20255
15237.0    19192
15108.0    17171
15235.0    15696
15236.0    12762
           ...
16117          1
93444          1
16351          1
15473          1
3055.0         1
Name: count, Length: 6683, dtype: int64

In [ ]:
# these cols are currently floats but can be represented as ints (no decimal values)
cols_to_int = ['PROPERTYHOUSENUM', 'PROPERTYZIP', 'YEARBLT', 'TOTALROOMS', 'BEDROOMS', 'FULLBATHS', 'HALFBATHS', 'CONDITION']
properties_c[(properties_c[cols_to_int].mod(1) > 0).any(axis=1)]

Empty DataFrame
Columns: [PROPERTYHOUSENUM, PROPERTYFRACTION, PROPERTYUNIT, PROPERTYADDRESS, PROPERTYCITY, PROPERTYSTATE, PROPERTYZIP, MUNICODE, MUNIDESC, NEIGHCODE, NEIGHDESC, SCHOOLCODE, SCHOOLDESC, LEGAL1, LEGAL2, LEGAL3, TAXCODE, TAXDESC, TAXSUBCODE, TAXSUBCODE_DESC, OWNERCODE, OWNERDESC, CLASS, USECODE, USEDESC, LOTAREA, SALEDATE, SALEPRICE, SALECODE, SALEDESC, PREVSALEDATE, PREVSALEPRICE, PREVSALEDATE2, PREVSALEPRICE2, CHANGENOTICEADDRESS1, CHANGENOTICEADDRESS2, CHANGENOTICEADDRESS3, CHANGENOTICEADDRESS4, COUNTYBUILDING, COUNTYLAND, COUNTYTOTAL, COUNTYEXEMPTBLDG, LOCALBUILDING, LOCALLAND, LOCALTOTAL, FAIRMARKETBUILDING, FAIRMARKETLAND, FAIRMARKETTOTAL, STYLE, STYLEDESC, STORIES, YEARBLT, TOTALROOMS, BEDROOMS, FULLBATHS, HALFBATHS, GRADE, GRADEDESC, CONDITION, CONDITIONDESC, CDU, CDUDESC, TAXYEAR]
Index: []

[0 rows x 63 columns]

In [1641]:
properties_c[cols_to_int] = properties_c[cols_to_int].astype('Int64')

In [1642]:
properties_c[cols_to_int].head()

,PROPERTYHOUSENUM,PROPERTYZIP,YEARBLT,TOTALROOMS,BEDROOMS,FULLBATHS,HALFBATHS,CONDITION
PARID,,,,,,,,
0001C00167000000,444,15222,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
0001C00200000001,501,15222,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
0001C00224000000,500,15222,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
0001C00228000000,400,15222,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
0001C00228000100,100,15222,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

### Datetime columns

In [1643]:
# datetime cols currently represented as strings
cols_to_dt = ['SALEDATE', 'PREVSALEDATE', 'PREVSALEDATE2']

In [1644]:
properties_c.loc[:, cols_to_dt] = properties_c[cols_to_dt].apply(pd.to_datetime)

In [1645]:
properties_c[cols_to_dt].head()

,SALEDATE,PREVSALEDATE,PREVSALEDATE2
PARID,,,
0001C00167000000,NaT,NaT,NaT
0001C00200000001,1984-01-24 00:00:00,NaT,NaT
0001C00224000000,2022-05-18 00:00:00,2013-12-12 00:00:00,2007-01-30 00:00:00
0001C00228000000,2018-07-11 00:00:00,1927-04-01 00:00:00,NaT
0001C00228000100,2016-02-25 00:00:00,NaT,NaT

In [1646]:
properties_c.info()

<class 'pandas.core.frame.DataFrame'>
Index: 584902 entries, 0001C00167000000 to 0185P00088000000
Data columns (total 63 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   PROPERTYHOUSENUM      584897 non-null  Int64
 1   PROPERTYFRACTION      584902 non-null  object
 2   PROPERTYUNIT          584902 non-null  object
 3   PROPERTYADDRESS       584902 non-null  object
 4   PROPERTYCITY          584899 non-null  object
 5   PROPERTYSTATE         584902 non-null  object
 6   PROPERTYZIP           584900 non-null  Int64
 7   MUNICODE              584902 non-null  int64
 8   MUNIDESC              584902 non-null  object
 9   NEIGHCODE             584902 non-null  object
 10  NEIGHDESC             583995 non-null  object
 11  SCHOOLCODE            584902 non-null  int64
 12  SCHOOLDESC            584902 non-null  object
 13  LEGAL1                584876 non-null  object
 14  LEGAL2                521078 non-null  object
 15  LEGAL3                336373 non-null  object
 16  TAXCODE               584902 non-null  object
 17  TAXDESC               584902 non-null  object
 18  TAXSUBCODE            1711 non-null    object
 19  TAXSUBCODE_DESC       1711 non-null    object
 20  OWNERCODE             584902 non-null  int64
 21  OWNERDESC             584902 non-null  object
 22  CLASS                 584902 non-null  object
 23  USECODE               584902 non-null  int64
 24  USEDESC               584902 non-null  object
 25  LOTAREA               584902 non-null  int64
 26  SALEDATE              578671 non-null  object
 27  SALEPRICE             576152 non-null  float64
 28  SALECODE              577884 non-null  object
 29  SALEDESC              576709 non-null  object
 30  PREVSALEDATE          421445 non-null  object
 31  PREVSALEPRICE         419605 non-null  float64
 32  PREVSALEDATE2         249500 non-null  object
 33  PREVSALEPRICE2        248745 non-null  float64
 34  CHANGENOTICEADDRESS1  584902 non-null  object
 35  CHANGENOTICEADDRESS2  584902 non-null  object
 36  CHANGENOTICEADDRESS3  584902 non-null  object
 37  CHANGENOTICEADDRESS4  572812 non-null  object
 38  COUNTYBUILDING        584902 non-null  int64
 39  COUNTYLAND            584902 non-null  int64
 40  COUNTYTOTAL           584902 non-null  int64
 41  COUNTYEXEMPTBLDG      584902 non-null  int64
 42  LOCALBUILDING         584902 non-null  int64
 43  LOCALLAND             584902 non-null  int64
 44  LOCALTOTAL            584902 non-null  int64
 45  FAIRMARKETBUILDING    584902 non-null  int64
 46  FAIRMARKETLAND        584902 non-null  int64
 47  FAIRMARKETTOTAL       584902 non-null  int64
 48  STYLE                 449180 non-null  object
 49  STYLEDESC             449180 non-null  object
 50  STORIES               449188 non-null  float64
 51  YEARBLT               449203 non-null  Int64
 52  TOTALROOMS            449098 non-null  Int64
 53  BEDROOMS              449159 non-null  Int64
 54  FULLBATHS             449090 non-null  Int64
 55  HALFBATHS             444524 non-null  Int64
 56  GRADE                 449181 non-null  object
 57  GRADEDESC             449181 non-null  object
 58  CONDITION             449120 non-null  Int64
 59  CONDITIONDESC         449120 non-null  object
 60  CDU                   449112 non-null  object
 61  CDUDESC               449112 non-null  object
 62  TAXYEAR               584902 non-null  int64
dtypes: Int64(8), float64(4), int64(16), object(35)
memory usage: 306.2+ MB

## String correction

In [1647]:
properties_c.select_dtypes('object').columns

Index(['PROPERTYFRACTION', 'PROPERTYUNIT', 'PROPERTYADDRESS', 'PROPERTYCITY',
       'PROPERTYSTATE', 'MUNIDESC', 'NEIGHCODE', 'NEIGHDESC', 'SCHOOLDESC',
       'LEGAL1', 'LEGAL2', 'LEGAL3', 'TAXCODE', 'TAXDESC', 'TAXSUBCODE',
       'TAXSUBCODE_DESC', 'OWNERDESC', 'CLASS', 'USEDESC', 'SALEDATE',
       'SALECODE', 'SALEDESC', 'PREVSALEDATE', 'PREVSALEDATE2',
       'CHANGENOTICEADDRESS1', 'CHANGENOTICEADDRESS2', 'CHANGENOTICEADDRESS3',
       'CHANGENOTICEADDRESS4', 'STYLE', 'STYLEDESC', 'GRADE', 'GRADEDESC',
       'CONDITIONDESC', 'CDU', 'CDUDESC'],
      dtype='object')

In [1648]:
# most 'uniform' string fields (e.g. those ending in 'code' or 'desc') do not appear to have inconsistencies in spelling or syntax
# open-ended fields (e.g. address, unit, fraction) are more prone to errors
cols_str_nonUniform = ['PROPERTYFRACTION', 'PROPERTYUNIT', 'PROPERTYADDRESS', 'PROPERTYCITY', 'MUNIDESC', 'CHANGENOTICEADDRESS1', 'CHANGENOTICEADDRESS2', 'CHANGENOTICEADDRESS3', 'CHANGENOTICEADDRESS4']

### Whitespace

In [1649]:
# replacing extra spaces with single spaces, trimming whitespace at ends
properties_c.loc[:, cols_str_nonUniform] = properties_c[cols_str_nonUniform].apply(lambda x: x.replace(r'\s+', " ", regex=True).str.strip())

In [1650]:
# verifying none of selected cols contain double spaces
properties_c[(properties_c[cols_str_nonUniform].apply(lambda x: x.str.count("  ")) > 0).any(axis=1)]

Empty DataFrame
Columns: [PROPERTYHOUSENUM, PROPERTYFRACTION, PROPERTYUNIT, PROPERTYADDRESS, PROPERTYCITY, PROPERTYSTATE, PROPERTYZIP, MUNICODE, MUNIDESC, NEIGHCODE, NEIGHDESC, SCHOOLCODE, SCHOOLDESC, LEGAL1, LEGAL2, LEGAL3, TAXCODE, TAXDESC, TAXSUBCODE, TAXSUBCODE_DESC, OWNERCODE, OWNERDESC, CLASS, USECODE, USEDESC, LOTAREA, SALEDATE, SALEPRICE, SALECODE, SALEDESC, PREVSALEDATE, PREVSALEPRICE, PREVSALEDATE2, PREVSALEPRICE2, CHANGENOTICEADDRESS1, CHANGENOTICEADDRESS2, CHANGENOTICEADDRESS3, CHANGENOTICEADDRESS4, COUNTYBUILDING, COUNTYLAND, COUNTYTOTAL, COUNTYEXEMPTBLDG, LOCALBUILDING, LOCALLAND, LOCALTOTAL, FAIRMARKETBUILDING, FAIRMARKETLAND, FAIRMARKETTOTAL, STYLE, STYLEDESC, STORIES, YEARBLT, TOTALROOMS, BEDROOMS, FULLBATHS, HALFBATHS, GRADE, GRADEDESC, CONDITION, CONDITIONDESC, CDU, CDUDESC, TAXYEAR]
Index: []

[0 rows x 63 columns]

In [1651]:
# some entries are stored as an empty string (or " ") rather than null
properties_c[properties_c.isin(["", " "]).any(axis=1)]

,PROPERTYHOUSENUM,PROPERTYFRACTION,PROPERTYUNIT,PROPERTYADDRESS,PROPERTYCITY,PROPERTYSTATE,PROPERTYZIP,MUNICODE,MUNIDESC,NEIGHCODE,...,BEDROOMS,FULLBATHS,HALFBATHS,GRADE,GRADEDESC,CONDITION,CONDITIONDESC,CDU,CDUDESC,TAXYEAR
PARID,,,,,,,,,,,,,,,,,,,,,
0001C00167000000,444,,,LIBERTY AVE,PITTSBURGH,PA,15222,101,1st Ward - PITTSBURGH,51C01,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026
0001C00200000001,501,,,STANWIX ST,PITTSBURGH,PA,15222,101,1st Ward - PITTSBURGH,51C01,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026
0001C00224000000,500,,,LIBERTY AVE,PITTSBURGH,PA,15222,101,1st Ward - PITTSBURGH,51C01,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026
0001C00228000000,400,-424,,STANWIX ST,PITTSBURGH,PA,15222,101,1st Ward - PITTSBURGH,51C01,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026
0001C00228000100,100,,,FORBES AVE,PITTSBURGH,PA,15222,101,1st Ward - PITTSBURGH,51C01,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0240M00012000000,1900,,,ADDISON AVE,WEST MIFFLIN,PA,15122,870,West Mifflin,87004,...,4,2,0,C+,AVERAGE +,3,AVERAGE,AV,AVERAGE,2026
0306E00154000000,1941,,,PENNSYLVANIA AVE,WEST MIFFLIN,PA,15122,870,West Mifflin,87004,...,3,1,0,C,AVERAGE,3,AVERAGE,AV,AVERAGE,2026
0310J00033000000,208,,,CRESTON DR,WEST MIFFLIN,PA,15122,870,West Mifflin,87005,...,3,1,1,C-,AVERAGE -,3,AVERAGE,AV,AVERAGE,2026
0240M00131000000,803,,,ANNA AVE,WEST MIFFLIN,PA,15122,870,West Mifflin,87004,...,2,1,1,C-,AVERAGE -,3,AVERAGE,AV,AVERAGE,2026
0185P00088000000,708,,,NORDEEN DR,WEST MIFFLIN,PA,15122,870,West Mifflin,87007,...,3,1,0,C,AVERAGE,3,AVERAGE,AV,AVERAGE,2026

In [1652]:
# replace empty and single-space strings with null
properties_c = properties_c.replace(r'^\s*$', np.nan, regex=True)

/var/folders/zj/02jlcxcn1dz5jm6ct_f_4wrr0000gn/T/ipykernel_37114/2990050401.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  properties_c = properties_c.replace(r'^\s*$', np.nan, regex=True)

In [1653]:
properties_c.head()

,PROPERTYHOUSENUM,PROPERTYFRACTION,PROPERTYUNIT,PROPERTYADDRESS,PROPERTYCITY,PROPERTYSTATE,PROPERTYZIP,MUNICODE,MUNIDESC,NEIGHCODE,...,BEDROOMS,FULLBATHS,HALFBATHS,GRADE,GRADEDESC,CONDITION,CONDITIONDESC,CDU,CDUDESC,TAXYEAR
PARID,,,,,,,,,,,,,,,,,,,,,
0001C00167000000,444,NaN,NaN,LIBERTY AVE,PITTSBURGH,PA,15222,101,1st Ward - PITTSBURGH,51C01,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026
0001C00200000001,501,NaN,NaN,STANWIX ST,PITTSBURGH,PA,15222,101,1st Ward - PITTSBURGH,51C01,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026
0001C00224000000,500,NaN,NaN,LIBERTY AVE,PITTSBURGH,PA,15222,101,1st Ward - PITTSBURGH,51C01,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026
0001C00228000000,400,-424,NaN,STANWIX ST,PITTSBURGH,PA,15222,101,1st Ward - PITTSBURGH,51C01,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026
0001C00228000100,100,NaN,NaN,FORBES AVE,PITTSBURGH,PA,15222,101,1st Ward - PITTSBURGH,51C01,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026

### Errors and inconsistencies

In [1101]:
from rapidfuzz import process, fuzz
import re

Before checking for string errors, remove properties with missing/invalid addresses, as these are not mappable and may indicate data that is invalid or redundant more generally.

In [1654]:
properties_c[(properties_c['PROPERTYHOUSENUM'] == 0) | properties_c['PROPERTYHOUSENUM'].isna() | properties_c['PROPERTYADDRESS'].isna()].head()

,PROPERTYHOUSENUM,PROPERTYFRACTION,PROPERTYUNIT,PROPERTYADDRESS,PROPERTYCITY,PROPERTYSTATE,PROPERTYZIP,MUNICODE,MUNIDESC,NEIGHCODE,...,BEDROOMS,FULLBATHS,HALFBATHS,GRADE,GRADEDESC,CONDITION,CONDITIONDESC,CDU,CDUDESC,TAXYEAR
PARID,,,,,,,,,,,,,,,,,,,,,
0001G00106000000,0,NaN,NaN,MARKET ST,PITTSBURGH,PA,15222,101,1st Ward - PITTSBURGH,51C02,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026
0001G00224000000,0,NaN,NaN,FORT PITT BLVD,PITTSBURGH,PA,15222,101,1st Ward - PITTSBURGH,10101,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026
0001H00040000000,0,NaN,NaN,BLVD OF THE ALLIES,PITTSBURGH,PA,15222,101,1st Ward - PITTSBURGH,51C01,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026
0001H00046000000,0,NaN,NaN,1ST AVE,PITTSBURGH,PA,15222,101,1st Ward - PITTSBURGH,51C02,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026
0001H00074000A00,0,NaN,NaN,BLVD OF THE ALLIES,PITTSBURGH,PA,15222,101,1st Ward - PITTSBURGH,51C02,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026

In [1823]:
props_mappable = properties_c[properties_c['PROPERTYHOUSENUM'] != 0].copy()

In [1824]:
props_mappable = props_mappable.dropna(subset=['PROPERTYHOUSENUM', 'PROPERTYADDRESS'])
print(f'Dropped: {len(properties_c) - len(props_mappable)} ({1 - len(props_mappable) / len(properties_c):.1%})')

Dropped: 85647 (14.6%)

#### City names

In [1825]:
# unique values for city field
# some places have multiple variations (e.g. mckees rocks, mc kees rocks)
# some entries invalid (null, non-string)
props_mappable['PROPERTYCITY'].sort_values(na_position='first').unique()

array([nan, '15216', 'ALLISON PARK', 'AMBRIDGE', 'ASPINWALL', 'BADEN',
       'BAIRDFORD', 'BAKERSTOWN', 'BELLE VERNON', 'BETHEL PARK',
       'BRACKENRIDGE', 'BRADDOCK', 'BRADFORD WOODS', 'BRADFORDWOODS',
       'BRIDGEVILLE', 'BUENA VISTA', 'BUNOLA', 'CARNEGIE', 'CECIL',
       'CHESWICK', 'CLAIRTON', 'CLINTON', 'CORAOPOLIS', 'COULTERS',
       'CREIGHTON', 'CRESCENT', 'CUDDY', 'CURTISVILLE', 'DRAVOSBURG',
       'DUQUESNE', 'EAST MC KEESPORT', 'EAST PITTSBURGH', 'ELIZABETH',
       'FAIR OAKS', 'FINLEYVILLE', 'FREEPORT', 'GIBSONIA', 'GLASSPORT',
       'GLENSHAW', 'GREENOCK', 'HARWICK', 'HOMESTEAD', 'IMPERIAL',
       'INDIANOLA', 'INGOMAR', 'IRWIN', 'JEFFERSON HILLS', 'LEETDALE',
       'LEETSDALE', 'MARS', 'MC DONALD', 'MC KEES ROCKS', 'MC KEESPORT',
       'MCDONALD', 'MCKEES ROCKS', 'MCKEESPORT', 'MONONGAHELA',
       'MONROEVILLE', 'MOON TOWNSHIP', 'MOON TWP', 'MORGAN', 'MUNHALL',
       'MURRYSVILLE', 'NATRONA HEIGHTS', 'NEW KENSINGTON',
       'NORTH BRADDOCK', 'NORTH FAYETTE', 'NORTH FAYETTE TOWNSHIP',
       'NORTH VERSAILLES', 'OAKDALE', 'OAKMONT', 'OBSERVATORY',
       'PENN HILLS', 'PITCAIRN', 'PITTSBURGH', 'PLUM', 'PORT VUE',
       'PRESTO', 'RANKIN', 'RURAL RIDGE', 'RUSSELLTON', 'SAXONBURG',
       'SEWICKLEY', 'SHARPSBURG', 'SOUTH PARK', 'SPRINGDALE', 'STURGEON',
       'SUTERSVILLE', 'TARENTUM', 'TRAFFORD', 'TURTLE CREEK', 'VALENCIA',
       'VERONA', 'WALL', 'WARRENDALE', 'WEST ELIZABETH', 'WEST HOMESTEAD',
       'WEST MIFFLIN', 'WEST NEWTON', 'WEST VIEW', 'WEXFORD', 'WHITAKER',
       'WHITE OAK', 'WILMERDING', 'WITAKER'], dtype=object)

In [1826]:
# can use counts to identify common/preferred form
print(props_mappable['PROPERTYCITY'].value_counts().loc['MC KEES ROCKS'])
print(props_mappable['PROPERTYCITY'].value_counts().loc['MCKEES ROCKS'])

10047
2

##### Handling invalids

In [1827]:
# only a few entries with completely invalid/missing city
props_mappable[(props_mappable['PROPERTYCITY'].isna()) | (props_mappable['PROPERTYCITY'] == '15216')]

,PROPERTYHOUSENUM,PROPERTYFRACTION,PROPERTYUNIT,PROPERTYADDRESS,PROPERTYCITY,PROPERTYSTATE,PROPERTYZIP,MUNICODE,MUNIDESC,NEIGHCODE,...,BEDROOMS,FULLBATHS,HALFBATHS,GRADE,GRADEDESC,CONDITION,CONDITIONDESC,CDU,CDUDESC,TAXYEAR
PARID,,,,,,,,,,,,,,,,,,,,,
0016N00001000000,1005,NaN,NaN,EAST ENTRY DR,15216,PA,15216,120,20th Ward - PITTSBURGH,51C78,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026
0016J00007000000,1001,NaN,NaN,E ENTRY DR,15216,PA,15216,120,20th Ward - PITTSBURGH,51C78,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026
0611L0006000T100,7920,NaN,NaN,PERRY HWY,NaN,PA,<NA>,940,Ross,55C24,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026

In [1828]:
# '15216' entries both list Pittsburgh in MUNIDESC
props_mappable.loc[props_mappable['PROPERTYCITY'] == '15216', 'PROPERTYCITY'] = 'PITTSBURGH'

In [1829]:
# 7920 PERRY HWY: all similar records have Pittsburgh as city
props_mappable[(props_mappable['MUNICODE'] == 940) & (props_mappable['PROPERTYADDRESS'] == 'PERRY HWY')]['PROPERTYCITY'].value_counts()

PROPERTYCITY
PITTSBURGH    164
Name: count, dtype: int64

In [1830]:
# manual correction
props_mappable.loc['0611L0006000T100', 'PROPERTYCITY'] = 'PITTSBURGH'

In [1831]:
props_mappable[(props_mappable['PROPERTYCITY'].isna()) | (props_mappable['PROPERTYCITY'] == '15216')]

Empty DataFrame
Columns: [PROPERTYHOUSENUM, PROPERTYFRACTION, PROPERTYUNIT, PROPERTYADDRESS, PROPERTYCITY, PROPERTYSTATE, PROPERTYZIP, MUNICODE, MUNIDESC, NEIGHCODE, NEIGHDESC, SCHOOLCODE, SCHOOLDESC, LEGAL1, LEGAL2, LEGAL3, TAXCODE, TAXDESC, TAXSUBCODE, TAXSUBCODE_DESC, OWNERCODE, OWNERDESC, CLASS, USECODE, USEDESC, LOTAREA, SALEDATE, SALEPRICE, SALECODE, SALEDESC, PREVSALEDATE, PREVSALEPRICE, PREVSALEDATE2, PREVSALEPRICE2, CHANGENOTICEADDRESS1, CHANGENOTICEADDRESS2, CHANGENOTICEADDRESS3, CHANGENOTICEADDRESS4, COUNTYBUILDING, COUNTYLAND, COUNTYTOTAL, COUNTYEXEMPTBLDG, LOCALBUILDING, LOCALLAND, LOCALTOTAL, FAIRMARKETBUILDING, FAIRMARKETLAND, FAIRMARKETTOTAL, STYLE, STYLEDESC, STORIES, YEARBLT, TOTALROOMS, BEDROOMS, FULLBATHS, HALFBATHS, GRADE, GRADEDESC, CONDITION, CONDITIONDESC, CDU, CDUDESC, TAXYEAR]
Index: []

[0 rows x 63 columns]

##### Standardizing names

In [1832]:
# invalids have now been excluded
props_mappable['PROPERTYCITY'].sort_values(na_position='first').unique()

array(['ALLISON PARK', 'AMBRIDGE', 'ASPINWALL', 'BADEN', 'BAIRDFORD',
       'BAKERSTOWN', 'BELLE VERNON', 'BETHEL PARK', 'BRACKENRIDGE',
       'BRADDOCK', 'BRADFORD WOODS', 'BRADFORDWOODS', 'BRIDGEVILLE',
       'BUENA VISTA', 'BUNOLA', 'CARNEGIE', 'CECIL', 'CHESWICK',
       'CLAIRTON', 'CLINTON', 'CORAOPOLIS', 'COULTERS', 'CREIGHTON',
       'CRESCENT', 'CUDDY', 'CURTISVILLE', 'DRAVOSBURG', 'DUQUESNE',
       'EAST MC KEESPORT', 'EAST PITTSBURGH', 'ELIZABETH', 'FAIR OAKS',
       'FINLEYVILLE', 'FREEPORT', 'GIBSONIA', 'GLASSPORT', 'GLENSHAW',
       'GREENOCK', 'HARWICK', 'HOMESTEAD', 'IMPERIAL', 'INDIANOLA',
       'INGOMAR', 'IRWIN', 'JEFFERSON HILLS', 'LEETDALE', 'LEETSDALE',
       'MARS', 'MC DONALD', 'MC KEES ROCKS', 'MC KEESPORT', 'MCDONALD',
       'MCKEES ROCKS', 'MCKEESPORT', 'MONONGAHELA', 'MONROEVILLE',
       'MOON TOWNSHIP', 'MOON TWP', 'MORGAN', 'MUNHALL', 'MURRYSVILLE',
       'NATRONA HEIGHTS', 'NEW KENSINGTON', 'NORTH BRADDOCK',
       'NORTH FAYETTE', 'NORTH FAYETTE TOWNSHIP', 'NORTH VERSAILLES',
       'OAKDALE', 'OAKMONT', 'OBSERVATORY', 'PENN HILLS', 'PITCAIRN',
       'PITTSBURGH', 'PLUM', 'PORT VUE', 'PRESTO', 'RANKIN',
       'RURAL RIDGE', 'RUSSELLTON', 'SAXONBURG', 'SEWICKLEY',
       'SHARPSBURG', 'SOUTH PARK', 'SPRINGDALE', 'STURGEON',
       'SUTERSVILLE', 'TARENTUM', 'TRAFFORD', 'TURTLE CREEK', 'VALENCIA',
       'VERONA', 'WALL', 'WARRENDALE', 'WEST ELIZABETH', 'WEST HOMESTEAD',
       'WEST MIFFLIN', 'WEST NEWTON', 'WEST VIEW', 'WEXFORD', 'WHITAKER',
       'WHITE OAK', 'WILMERDING', 'WITAKER'], dtype=object)

Replace abbreviations in city names

In [1833]:
city_abbrevs = {
        'N' : 'NORTH',
        'E' : 'EAST',
        'S' : 'SOUTH',
        'W' : 'WEST',
        'TWP' : 'TOWNSHIP'
    }

In [1834]:
def map_phrases(x, mapping: dict):
    for abbr, repl in mapping.items():
        x = re.sub(rf'\b{abbr}\b', repl, x)
    return x

In [1835]:
props_mappable['PROPERTYCITY'] = props_mappable['PROPERTYCITY'].apply(map_phrases, mapping=city_abbrevs)

In [1836]:
props_mappable['PROPERTYCITY'].sort_values(na_position='first').unique()

array(['ALLISON PARK', 'AMBRIDGE', 'ASPINWALL', 'BADEN', 'BAIRDFORD',
       'BAKERSTOWN', 'BELLE VERNON', 'BETHEL PARK', 'BRACKENRIDGE',
       'BRADDOCK', 'BRADFORD WOODS', 'BRADFORDWOODS', 'BRIDGEVILLE',
       'BUENA VISTA', 'BUNOLA', 'CARNEGIE', 'CECIL', 'CHESWICK',
       'CLAIRTON', 'CLINTON', 'CORAOPOLIS', 'COULTERS', 'CREIGHTON',
       'CRESCENT', 'CUDDY', 'CURTISVILLE', 'DRAVOSBURG', 'DUQUESNE',
       'EAST MC KEESPORT', 'EAST PITTSBURGH', 'ELIZABETH', 'FAIR OAKS',
       'FINLEYVILLE', 'FREEPORT', 'GIBSONIA', 'GLASSPORT', 'GLENSHAW',
       'GREENOCK', 'HARWICK', 'HOMESTEAD', 'IMPERIAL', 'INDIANOLA',
       'INGOMAR', 'IRWIN', 'JEFFERSON HILLS', 'LEETDALE', 'LEETSDALE',
       'MARS', 'MC DONALD', 'MC KEES ROCKS', 'MC KEESPORT', 'MCDONALD',
       'MCKEES ROCKS', 'MCKEESPORT', 'MONONGAHELA', 'MONROEVILLE',
       'MOON TOWNSHIP', 'MORGAN', 'MUNHALL', 'MURRYSVILLE',
       'NATRONA HEIGHTS', 'NEW KENSINGTON', 'NORTH BRADDOCK',
       'NORTH FAYETTE', 'NORTH FAYETTE TOWNSHIP', 'NORTH VERSAILLES',
       'OAKDALE', 'OAKMONT', 'OBSERVATORY', 'PENN HILLS', 'PITCAIRN',
       'PITTSBURGH', 'PLUM', 'PORT VUE', 'PRESTO', 'RANKIN',
       'RURAL RIDGE', 'RUSSELLTON', 'SAXONBURG', 'SEWICKLEY',
       'SHARPSBURG', 'SOUTH PARK', 'SPRINGDALE', 'STURGEON',
       'SUTERSVILLE', 'TARENTUM', 'TRAFFORD', 'TURTLE CREEK', 'VALENCIA',
       'VERONA', 'WALL', 'WARRENDALE', 'WEST ELIZABETH', 'WEST HOMESTEAD',
       'WEST MIFFLIN', 'WEST NEWTON', 'WEST VIEW', 'WEXFORD', 'WHITAKER',
       'WHITE OAK', 'WILMERDING', 'WITAKER'], dtype=object)

Correct spelling/formatting variations

In [2693]:
def consolidate_names(df : pd.DataFrame, col: str, block_by = None, threshold : int = 85, scorer=fuzz.ratio):
    names = pd.DataFrame({'val': df[col]})
    results_map = {}
    
    # block by elements
    names['block'] = block_by
    
    for _, block_df in names.groupby('block'):
        # unique names ordered by frequency
        uniques = block_df['val'].value_counts().index.to_list()
        
        mapping = {}
        used = set()
        
        # iterate through unique names (in order of frequency)
        for canonical in uniques:
            # skip if name already matched (variant of a canonical name)
            if canonical in used:
                continue
            # identify similar strings (fuzzy matching)
            matches = process.extract(
                canonical,
                uniques,
                scorer=scorer,
                score_cutoff=threshold
            )
            # get name values from match arrays
            match_names = [match[0] for match in matches]
            # construct dict mapping variant names to canonical name (highest freq)
            for name in match_names:
                mapping[name] = canonical
                used.add(name)
                # print any changed items
                # if name != canonical:
                #     print(f'{name} -> {canonical}')
            
        results_map.update(mapping)
                
    results = df[col].map(results_map)
    
    return results, results_map

In [ ]:
std_city = consolidate_names(props_mappable, 'PROPERTYCITY', 82)

MCKEESPORT -> MC KEESPORT
MCKEES ROCKS -> MC KEES ROCKS
MCDONALD -> MC DONALD
LEETDALE -> LEETSDALE
BRADFORDWOODS -> BRADFORD WOODS
WHITAKER -> WITAKER

In [1839]:
props_mappable['PROPERTYCITY'] = std_city[0]

In [1840]:
# additional manual correction
props_mappable.loc[props_mappable['PROPERTYCITY'] == 'NORTH FAYETTE', 'PROPERTYCITY'] = 'NORTH FAYETTE TOWNSHIP'
props_mappable.loc[props_mappable['PROPERTYCITY'] == 'WITAKER', 'PROPERTYCITY'] = 'WHITAKER'

In [1841]:
props_mappable['PROPERTYCITY'].value_counts().sort_index().to_dict()

{'ALLISON PARK': 9181,
 'AMBRIDGE': 390,
 'ASPINWALL': 3,
 'BADEN': 602,
 'BAIRDFORD': 143,
 'BAKERSTOWN': 157,
 'BELLE VERNON': 17,
 'BETHEL PARK': 11696,
 'BRACKENRIDGE': 1401,
 'BRADDOCK': 3799,
 'BRADFORD WOODS': 528,
 'BRIDGEVILLE': 6937,
 'BUENA VISTA': 440,
 'BUNOLA': 130,
 'CARNEGIE': 8426,
 'CECIL': 23,
 'CHESWICK': 4028,
 'CLAIRTON': 7978,
 'CLINTON': 815,
 'CORAOPOLIS': 16625,
 'COULTERS': 96,
 'CREIGHTON': 531,
 'CRESCENT': 1149,
 'CUDDY': 246,
 'CURTISVILLE': 1,
 'DRAVOSBURG': 689,
 'DUQUESNE': 2343,
 'EAST MC KEESPORT': 951,
 'EAST PITTSBURGH': 1346,
 'ELIZABETH': 4926,
 'FAIR OAKS': 1,
 'FINLEYVILLE': 815,
 'FREEPORT': 13,
 'GIBSONIA': 11479,
 'GLASSPORT': 2026,
 'GLENSHAW': 5936,
 'GREENOCK': 171,
 'HARWICK': 484,
 'HOMESTEAD': 8107,
 'IMPERIAL': 3608,
 'INDIANOLA': 250,
 'INGOMAR': 1,
 'IRWIN': 54,
 'JEFFERSON HILLS': 23,
 'LEETSDALE': 579,
 'MARS': 1395,
 'MC DONALD': 3505,
 'MC KEES ROCKS': 10049,
 'MC KEESPORT': 17097,
 'MONONGAHELA': 779,
 'MONROEVILLE': 10523,
 'MOON TOWNSHIP': 2,
 'MORGAN': 192,
 'MUNHALL': 29,
 'MURRYSVILLE': 32,
 'NATRONA HEIGHTS': 5087,
 'NEW KENSINGTON': 2026,
 'NORTH BRADDOCK': 7,
 'NORTH FAYETTE TOWNSHIP': 8,
 'NORTH VERSAILLES': 4376,
 'OAKDALE': 4877,
 'OAKMONT': 2804,
 'OBSERVATORY': 1,
 'PENN HILLS': 1,
 'PITCAIRN': 1218,
 'PITTSBURGH': 266396,
 'PLUM': 1,
 'PORT VUE': 1,
 'PRESTO': 755,
 'RANKIN': 5,
 'RURAL RIDGE': 82,
 'RUSSELLTON': 441,
 'SAXONBURG': 3,
 'SEWICKLEY': 8560,
 'SHARPSBURG': 1,
 'SOUTH PARK': 4328,
 'SPRINGDALE': 1857,
 'STURGEON': 163,
 'SUTERSVILLE': 30,
 'TARENTUM': 4606,
 'TRAFFORD': 36,
 'TURTLE CREEK': 2559,
 'VALENCIA': 128,
 'VERONA': 7175,
 'WALL': 291,
 'WARRENDALE': 351,
 'WEST ELIZABETH': 298,
 'WEST HOMESTEAD': 5,
 'WEST MIFFLIN': 8218,
 'WEST NEWTON': 27,
 'WEST VIEW': 2,
 'WEXFORD': 8948,
 'WHITAKER': 2,
 'WHITE OAK': 9,
 'WILMERDING': 825}

#### Addresses

In [3478]:
# will need to check against address points dataset
# address_points = geopandas.read_file('data/AddressPoints_clean.shp.zip')

Checking for variations in formatting/spelling

In [3479]:
# checking addresses with number in street name
r = re.compile(r'\b\d+\b')
pd.Series(filter(r.search, props_mappable['PROPERTYADDRESS'])).sort_values().unique()

array(['43RD 1/2 ST', 'FRAZER 2 LN', 'I 376 WB', 'OLD ROUTE 8',
       'PA TPK 43 NB', 'ROUTE 8', 'ROUTE 910', 'STATE ROUTE 151',
       'STATE ROUTE 51', 'STATE ROUTE 837', 'STATE ROUTE 885',
       'STATE ROUTE 906', 'STATE ROUTE 908', 'STATE ROUTE 908 EXT',
       'US ROUTE 30'], dtype=object)

In [3480]:
# manual consolidation (based on values present in address points dataset)
props_mappable.loc['1355E00235000000', 'PROPERTYADDRESS'] = 'ROUTE 8'
props_mappable.loc[['1626H00279000000', '1469A00212000000'], 'PROPERTYADDRESS'] = 'US ROUTE 30'

In [3481]:
# while unabbreviated street names (e.g. 'STREET' instead of 'ST') could be irregular, it seems they correlate with address points entries
r = re.compile(r'\bSTREET\b')
print(pd.Series(filter(r.search, props_mappable['PROPERTYADDRESS'])).sort_values().unique()[:10])
print(pd.Series(filter(r.search, address_points['ST_NAME'])).sort_values().unique()[:10])

['10TH STREET BYP' '23RD STREET EXT' '2ND STREET EXT' '5TH STREET EXT'
 'ALICE STREET EXT' 'ARCH STREET EXT' 'BANK STREET EXT' 'BEECH STREET EXT'
 'BLUFF STREET EXT' 'BUTLER STREET EXT']
['10TH STREET' '23RD STREET' '2ND STREET' '5TH STREET' 'ALICE STREET'
 'ARCH STREET' 'BANK STREET' 'BEECH STREET' 'BLUFF STREET' 'BUTLER STREET']

#### ZIP Code

In [1846]:
# unique values for zip field
# no invalid / erroneous entries, but nulls are present
props_mappable['PROPERTYZIP'].sort_values(na_position='first').unique()

<IntegerArray>
[ <NA>, 15003, 15005, 15006, 15007, 15012, 15014, 15015, 15017, 15018,
 ...
 15282, 15290, 15321, 15332, 15642, 15668, 16046, 16056, 16059, 16229]
Length: 127, dtype: Int64

In [1847]:
props_mappable[props_mappable['PROPERTYZIP'].isna()]

,PROPERTYHOUSENUM,PROPERTYFRACTION,PROPERTYUNIT,PROPERTYADDRESS,PROPERTYCITY,PROPERTYSTATE,PROPERTYZIP,MUNICODE,MUNIDESC,NEIGHCODE,...,BEDROOMS,FULLBATHS,HALFBATHS,GRADE,GRADEDESC,CONDITION,CONDITIONDESC,CDU,CDUDESC,TAXYEAR
PARID,,,,,,,,,,,,,,,,,,,,,
0611L0006000T100,7920,NaN,NaN,PERRY HWY,PITTSBURGH,PA,<NA>,940,Ross,55C24,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026

In [1848]:
# manual correction based on Google Maps location
props_mappable.loc['0611L0006000T100', 'PROPERTYZIP'] = 15237

## Merging

### Preparation

Handling duplicates

In [1849]:
# all address fields duplicated
props_mappable[props_mappable.duplicated(
    subset=['PROPERTYHOUSENUM', 'PROPERTYFRACTION', 'PROPERTYADDRESS', 'PROPERTYUNIT', 'PROPERTYCITY', 'PROPERTYZIP'],
    keep=False)]\
        .sort_values(['PROPERTYZIP', 'PROPERTYCITY', 'PROPERTYADDRESS', 'PROPERTYHOUSENUM', 'PROPERTYFRACTION', 'PROPERTYUNIT'])\
        .head()

,PROPERTYHOUSENUM,PROPERTYFRACTION,PROPERTYUNIT,PROPERTYADDRESS,PROPERTYCITY,PROPERTYSTATE,PROPERTYZIP,MUNICODE,MUNIDESC,NEIGHCODE,...,BEDROOMS,FULLBATHS,HALFBATHS,GRADE,GRADEDESC,CONDITION,CONDITIONDESC,CDU,CDUDESC,TAXYEAR
PARID,,,,,,,,,,,,,,,,,,,,,
0934K00041000000,19,NaN,NaN,AMBRIDGE AVE,AMBRIDGE,PA,15003,921,Leet,92103,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026
0934K00044000000,19,NaN,NaN,AMBRIDGE AVE,AMBRIDGE,PA,15003,921,Leet,92103,...,2,1,0,D+,BELOW AVERAGE +,3,AVERAGE,AV,AVERAGE,2026
0934G00186000000,512,NaN,NaN,AMBRIDGE AVE,AMBRIDGE,PA,15003,921,Leet,92103,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026
0934G00193000000,512,NaN,NaN,AMBRIDGE AVE,AMBRIDGE,PA,15003,921,Leet,92103,...,4,1,1,C,AVERAGE,3,AVERAGE,AV,AVERAGE,2026
0934C00262000000,566,NaN,NaN,AMBRIDGE AVE,AMBRIDGE,PA,15003,883,Bell Acres,88303,...,3,2,0,C,AVERAGE,3,AVERAGE,AV,AVERAGE,2026

In [1850]:
# drop exact duplicates
props_mappable = props_mappable.drop_duplicates(
    subset=['PROPERTYHOUSENUM', 'PROPERTYFRACTION', 'PROPERTYADDRESS', 'PROPERTYUNIT', 'PROPERTYCITY', 'PROPERTYZIP'],
    keep='last')

In [1851]:
# all address fields except city name duplicated; some of these may be duplicated addresses, others are actually distinct
props_mappable[props_mappable.duplicated(
    subset=['PROPERTYHOUSENUM', 'PROPERTYFRACTION', 'PROPERTYADDRESS', 'PROPERTYUNIT', 'PROPERTYZIP'],
    keep=False)]\
        .sort_values(['PROPERTYHOUSENUM', 'PROPERTYFRACTION', 'PROPERTYADDRESS', 'PROPERTYUNIT', 'PROPERTYZIP'])\
        .head()

,PROPERTYHOUSENUM,PROPERTYFRACTION,PROPERTYUNIT,PROPERTYADDRESS,PROPERTYCITY,PROPERTYSTATE,PROPERTYZIP,MUNICODE,MUNIDESC,NEIGHCODE,...,BEDROOMS,FULLBATHS,HALFBATHS,GRADE,GRADEDESC,CONDITION,CONDITIONDESC,CDU,CDUDESC,TAXYEAR
PARID,,,,,,,,,,,,,,,,,,,,,
0169L00227000000,23,NaN,NaN,5TH ST,ASPINWALL,PA,15215,801,Aspinwall,80103,...,2,1,1,C,AVERAGE,3,AVERAGE,FR,FAIR,2026
0167S00143000000,23,NaN,NaN,5TH ST,PITTSBURGH,PA,15215,852,Sharpsburg,85202,...,3,1,0,C-,AVERAGE -,3,AVERAGE,AV,AVERAGE,2026
0497S00015000000,90,NaN,NaN,DAVIS RD,CORAOPOLIS,PA,15108,929,North Fayette,92905,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026
0497S00016000000,90,NaN,NaN,DAVIS RD,NORTH FAYETTE TOWNSHIP,PA,15108,929,North Fayette,92905,...,2,1,1,C,AVERAGE,3,AVERAGE,AV,AVERAGE,2026
0169H00022000000,200,NaN,NaN,10TH ST,ASPINWALL,PA,15215,801,Aspinwall,80101,...,2,1,1,C+,AVERAGE +,2,GOOD,GD,GOOD,2026

Creating key to merge on; using full address + zip code as merge key initially, no city/municipality as naming is inconsistent between each.

In [1852]:
def combine_fields(x):
    values = [str(val) for val in x if val != '']
    combined = ' '.join(values)
    return combined

In [1853]:
prop_merge_fields = ['PROPERTYHOUSENUM', 'PROPERTYFRACTION', 'PROPERTYADDRESS', 'PROPERTYUNIT', 'PROPERTYZIP']
props_mappable['GEO_MERGE_KEY'] = props_mappable[prop_merge_fields].fillna('').apply(combine_fields, axis=1)

In [1854]:
props_mappable['GEO_MERGE_KEY'].head()

PARID
0001C00167000000                444 LIBERTY AVE 15222
0001C00200000001                 501 STANWIX ST 15222
0001C00228000000            400 -424 STANWIX ST 15222
0001C00228000100                 100 FORBES AVE 15222
0001G00224050600    151 FORT PITT BLVD UNIT 506 15222
Name: GEO_MERGE_KEY, dtype: object

Repeating for address points

In [1855]:
addr_merge_fields = ['FULL_ADDRE', 'ZIP_CODE']
address_points['GEO_MERGE_KEY'] = address_points[addr_merge_fields].fillna('').apply(combine_fields, axis=1)

In [1856]:
address_points['GEO_MERGE_KEY'].head()

0    106 SAXONWALD LN 15234
1         143 RANA LN 15044
2         155 RANA LN 15044
3        233 ROSE CIR 15044
4        206 ROSE CIR 15044
Name: GEO_MERGE_KEY, dtype: object

#### Duplicate keys

Some duplicates present in merge key (same address and zip code, varying only by city name); include city name in merge key for these.

In [1857]:
# same address and zip code, vary by city name
props_mappable[props_mappable['GEO_MERGE_KEY'].duplicated(keep=False)].sort_values('GEO_MERGE_KEY').head()

,PROPERTYHOUSENUM,PROPERTYFRACTION,PROPERTYUNIT,PROPERTYADDRESS,PROPERTYCITY,PROPERTYSTATE,PROPERTYZIP,MUNICODE,MUNIDESC,NEIGHCODE,...,FULLBATHS,HALFBATHS,GRADE,GRADEDESC,CONDITION,CONDITIONDESC,CDU,CDUDESC,TAXYEAR,GEO_MERGE_KEY
PARID,,,,,,,,,,,,,,,,,,,,,
0883K00132000000,1210,NaN,NaN,GILL HALL RD,CLAIRTON,PA,15025,878,Jefferson Hills,87803,...,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026,1210 GILL HALL RD 15025
0883K00142000000,1210,NaN,NaN,GILL HALL RD,JEFFERSON HILLS,PA,15025,878,Jefferson Hills,87803,...,1,1,C,AVERAGE,3,AVERAGE,AV,AVERAGE,2026,1210 GILL HALL RD 15025
2011G00094000000,1363,-1367,NaN,LOGAN RD,TARENTUM,PA,15044,952,West Deer,95203,...,2,1,C,AVERAGE,3,AVERAGE,AV,AVERAGE,2026,1363 -1367 LOGAN RD 15044
2011G00092000000,1363,-1367,NaN,LOGAN RD,GIBSONIA,PA,15044,952,West Deer,95203,...,<NA>,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,2026,1363 -1367 LOGAN RD 15044
0319D00175000000,1630,NaN,NaN,N HIGHLAND RD,PITTSBURGH,PA,15241,950,Upper St. Clair,95004,...,2,1,B-,GOOD -,3,AVERAGE,AV,AVERAGE,2026,1630 N HIGHLAND RD 15241

In [1892]:
props_dupl_key = props_mappable[props_mappable['GEO_MERGE_KEY'].duplicated(keep=False)]

In [1923]:
print(len(props_dupl_key))

24

In [3152]:
# Match city names between properties and address points
def match_names(col : pd.Series, choices, scorer=fuzz.token_set_ratio, threshold=90):
    uniques = list(col.unique())
    if isinstance(choices, pd.Series):
        choices = choices.unique()
    mapping = {}
    
    for name in uniques:
        match = process.extractOne(
            name,
            choices,
            scorer=scorer,
            score_cutoff=threshold
        )
        if match:
            match_name = match[0]
            mapping[name] = match_name
        else:
            mapping[name] = name
    
    results = col.map(mapping)
    
    return results, mapping

In [1893]:
matched_city = match_names(props_dupl_key['PROPERTYCITY'], address_points['MUNICIPALI'].unique())

In [ ]:
# display mapping
matched_city[1]

{'ASPINWALL': 'ASPINWALL BOROUGH',
 'SHARPSBURG': 'SHARPSBURG BOROUGH',
 'PITTSBURGH': 'CITY OF PITTSBURGH',
 'WILMERDING': 'WILMERDING BOROUGH',
 'HOMESTEAD': 'HOMESTEAD BOROUGH',
 'WALL': 'WALL BOROUGH',
 'WHITAKER': 'WHITAKER BOROUGH',
 'CLAIRTON': 'CITY OF CLAIRTON',
 'JEFFERSON HILLS': 'JEFFERSON HILLS BOROUGH',
 'SEWICKLEY': 'SEWICKLEY HILLS BOROUGH',
 'CORAOPOLIS': 'CORAOPOLIS BOROUGH',
 'BETHEL PARK': 'BETHEL PARK MUNICIPALITY',
 'NORTH FAYETTE TOWNSHIP': 'NORTH FAYETTE TOWNSHIP',
 'GIBSONIA': 'GIBSONIA',
 'TARENTUM': 'TARENTUM BOROUGH'}

In [1901]:
props_dupl_key.loc[:, 'MERGE_KEY_CITY'] = matched_city[0]
props_dupl_key.head(1)

,PROPERTYHOUSENUM,PROPERTYFRACTION,PROPERTYUNIT,PROPERTYADDRESS,PROPERTYCITY,PROPERTYSTATE,PROPERTYZIP,MUNICODE,MUNIDESC,NEIGHCODE,...,HALFBATHS,GRADE,GRADEDESC,CONDITION,CONDITIONDESC,CDU,CDUDESC,TAXYEAR,GEO_MERGE_KEY,MERGE_KEY_CITY
PARID,,,,,,,,,,,,,,,,,,,,,
0169L00227000000,23,NaN,NaN,5TH ST,ASPINWALL,PA,15215,801,Aspinwall,80103,...,1,C,AVERAGE,3,AVERAGE,FR,FAIR,2026,23 5TH ST 15215,ASPINWALL BOROUGH

In [1906]:
# generate new merge keys with city for duplicate cases
prop_merge_fields_ext = ['PROPERTYHOUSENUM', 'PROPERTYFRACTION', 'PROPERTYADDRESS', 'PROPERTYUNIT', 'MERGE_KEY_CITY', 'PROPERTYZIP']
props_dupl_key.loc[:, 'GEO_MERGE_KEY'] = props_dupl_key[prop_merge_fields_ext].fillna('').apply(combine_fields, axis=1)
props_dupl_key['GEO_MERGE_KEY'].head()

PARID
0169L00227000000       23 5TH ST ASPINWALL BOROUGH 15215
0169H00022000000     200 10TH ST ASPINWALL BOROUGH 15215
0169H00024000000     206 10TH ST ASPINWALL BOROUGH 15215
0168J00079000000    206 10TH ST SHARPSBURG BOROUGH 15215
0168J00076000000    200 10TH ST CITY OF PITTSBURGH 15215
Name: GEO_MERGE_KEY, dtype: object

In [1907]:
# update in original df
props_mappable.loc[props_dupl_key.index, 'GEO_MERGE_KEY'] = props_dupl_key['GEO_MERGE_KEY']

In [1908]:
# duplicates no longer present
props_mappable[props_mappable['GEO_MERGE_KEY'].duplicated(keep=False)]

Empty DataFrame
Columns: [PROPERTYHOUSENUM, PROPERTYFRACTION, PROPERTYUNIT, PROPERTYADDRESS, PROPERTYCITY, PROPERTYSTATE, PROPERTYZIP, MUNICODE, MUNIDESC, NEIGHCODE, NEIGHDESC, SCHOOLCODE, SCHOOLDESC, LEGAL1, LEGAL2, LEGAL3, TAXCODE, TAXDESC, TAXSUBCODE, TAXSUBCODE_DESC, OWNERCODE, OWNERDESC, CLASS, USECODE, USEDESC, LOTAREA, SALEDATE, SALEPRICE, SALECODE, SALEDESC, PREVSALEDATE, PREVSALEPRICE, PREVSALEDATE2, PREVSALEPRICE2, CHANGENOTICEADDRESS1, CHANGENOTICEADDRESS2, CHANGENOTICEADDRESS3, CHANGENOTICEADDRESS4, COUNTYBUILDING, COUNTYLAND, COUNTYTOTAL, COUNTYEXEMPTBLDG, LOCALBUILDING, LOCALLAND, LOCALTOTAL, FAIRMARKETBUILDING, FAIRMARKETLAND, FAIRMARKETTOTAL, STYLE, STYLEDESC, STORIES, YEARBLT, TOTALROOMS, BEDROOMS, FULLBATHS, HALFBATHS, GRADE, GRADEDESC, CONDITION, CONDITIONDESC, CDU, CDUDESC, TAXYEAR, GEO_MERGE_KEY]
Index: []

[0 rows x 64 columns]

In [1864]:
address_points[address_points['GEO_MERGE_KEY'].duplicated(keep=False)].sort_values('GEO_MERGE_KEY').head()

,FEATURE_KE,ADDRESS_ID,PARENT_ID,STREET_ID,ADDRESS_TY,STATUS,ADDR_NUM_P,ADDR_NUM,ADDR_NUM_S,ST_PREMODI,...,EDIT_USER,SOURCE,EXP_FLAG,FULL_ADDRE,ST_SUFFIX,COMBINED_A,FULL_ADDR_,COMBINED_1,geometry,GEO_MERGE_KEY
487941,557231,557231,0,481,5,ACTIVE,None,1,None,None,...,T096517,MUNICIPALITY,None,1 5TH ST,None,1 5TH ST ASPINWALL BOROUGH 15215,1 5TH ST,1 5TH ST ASPINWALL BOROUGH 15215,POINT (1368328.894 430424.566),1 5TH ST 15215
151311,169561,169561,0,499,1,ACTIVE,None,1,None,None,...,T096517,EAMS,None,1 5TH ST,None,1 5TH ST SHARPSBURG BOROUGH 15215,1 5TH ST,1 5TH ST SHARPSBURG BOROUGH 15215,POINT (1360578.6 430123.9),1 5TH ST 15215
309045,346877,346877,0,6884,1,ACTIVE,None,1,None,None,...,t096517,EAMS,ACM,1 DOUGLAS ST,None,1 DOUGLAS ST CITY OF MCKEESPORT 15132,1 DOUGLAS ST,1 DOUGLAS ST CITY OF MCKEESPORT 15132,POINT (1385780.4 366585.9),1 DOUGLAS ST 15132
308125,345825,345825,0,6886,1,ACTIVE,None,1,None,None,...,T096517,EAMS,ACM,1 DOUGLAS ST,None,1 DOUGLAS ST VERSAILLES BOROUGH 15132,1 DOUGLAS ST,1 DOUGLAS ST VERSAILLES BOROUGH 15132,POINT (1386007.3 366238.5),1 DOUGLAS ST 15132
653381,222211,222211,0,19109,1,ACTIVE,None,10,None,None,...,t096517,EAMS,DUP,10 PLUM ST,None,10 PLUM ST VERONA BOROUGH 15147,10 PLUM ST,10 PLUM ST VERONA BOROUGH 15147,POINT (1389148.509 436067.797),10 PLUM ST 15147

In [1909]:
# new merge key with city for duplicates (names now match between each)
addr_dupl_key = address_points[address_points['GEO_MERGE_KEY'].duplicated(keep=False)]
addr_merge_fields_ext = ['FULL_ADDRE', 'MUNICIPALI', 'ZIP_CODE']
addr_dupl_key.loc[:, 'GEO_MERGE_KEY'] = addr_dupl_key[addr_merge_fields_ext].fillna('').apply(combine_fields, axis=1)
addr_dupl_key['GEO_MERGE_KEY'].head()

14218                  144 RIDGE AVE BELLEVUE BOROUGH 15202
54807     301 SOUTH HILLS VLG BETHEL PARK MUNICIPALITY 1...
85840                  135 RIDGE AVE BELLEVUE BOROUGH 15202
119691                2510 MIDDLE RD HAMPTON TOWNSHIP 15116
119768                2510 MIDDLE RD INDIANA TOWNSHIP 15116
Name: GEO_MERGE_KEY, dtype: object

In [1910]:
address_points.loc[addr_dupl_key.index, 'GEO_MERGE_KEY'] = addr_dupl_key['GEO_MERGE_KEY']

In [1911]:
address_points[address_points['GEO_MERGE_KEY'].duplicated(keep=False)]

Empty GeoDataFrame
Columns: [FEATURE_KE, ADDRESS_ID, PARENT_ID, STREET_ID, ADDRESS_TY, STATUS, ADDR_NUM_P, ADDR_NUM, ADDR_NUM_S, ST_PREMODI, ST_PREFIX, ST_PRETYPE, ST_NAME, ST_TYPE, ST_POSTMOD, UNIT_TYPE, UNIT, FLOOR, MUNICIPALI, COUNTY, STATE, ZIP_CODE, EDIT_DATE, EDIT_USER, SOURCE, EXP_FLAG, FULL_ADDRE, ST_SUFFIX, COMBINED_A, FULL_ADDR_, COMBINED_1, geometry, GEO_MERGE_KEY]
Index: []

[0 rows x 33 columns]

### Exact matches

In [1912]:
# merge on address + zip matches (retain index)
props_geo = props_mappable.reset_index().merge(address_points, how='inner', on='GEO_MERGE_KEY').set_index('PARID')

In [1924]:
props_not_merged = props_mappable[~props_mappable.index.isin(props_geo.index)]
print(f'Not merged: {len(props_not_merged)} ({len(props_not_merged) / len(props_mappable):.1%})')

Not merged: 13667 (2.8%)

In [1925]:
props_geo.head(3)

,PROPERTYHOUSENUM,PROPERTYFRACTION,PROPERTYUNIT,PROPERTYADDRESS,PROPERTYCITY,PROPERTYSTATE,PROPERTYZIP,MUNICODE,MUNIDESC,NEIGHCODE,...,EDIT_DATE,EDIT_USER,SOURCE,EXP_FLAG,FULL_ADDRE,ST_SUFFIX,COMBINED_A,FULL_ADDR_,COMBINED_1,geometry
PARID,,,,,,,,,,,,,,,,,,,,,
0001C00167000000,444,NaN,NaN,LIBERTY AVE,PITTSBURGH,PA,15222,101,1st Ward - PITTSBURGH,51C01,...,2013-08-29,t096517,EAMS,None,444 LIBERTY AVE,None,444 LIBERTY AVE CITY OF PITTSBURGH 15222,444 LIBERTY AVE,444 LIBERTY AVE CITY OF PITTSBURGH 15222,POINT (1340992.9 411472.3)
0001C00200000001,501,NaN,NaN,STANWIX ST,PITTSBURGH,PA,15222,101,1st Ward - PITTSBURGH,51C01,...,2016-08-04,t096517,MUNICIPALITY,None,501 STANWIX ST,None,501 STANWIX ST CITY OF PITTSBURGH 15222,501 STANWIX ST,501 STANWIX ST CITY OF PITTSBURGH 15222,POINT (1341162.909 411783.778)
0001C00228000100,100,NaN,NaN,FORBES AVE,PITTSBURGH,PA,15222,101,1st Ward - PITTSBURGH,51C01,...,2017-01-27,t096517,MUNICIPALITY,AOR,100 FORBES AVE,None,100 FORBES AVE CITY OF PITTSBURGH 15222,100 FORBES AVE,100 FORBES AVE CITY OF PITTSBURGH 15222,POINT (1341271.258 411482.849)

In [1926]:
len(props_geo)

470392

In [1927]:
# no duplicate parcels (merged 1 to 1)
props_geo.loc[props_geo.index.duplicated(keep=False)]

Empty DataFrame
Columns: [PROPERTYHOUSENUM, PROPERTYFRACTION, PROPERTYUNIT, PROPERTYADDRESS, PROPERTYCITY, PROPERTYSTATE, PROPERTYZIP, MUNICODE, MUNIDESC, NEIGHCODE, NEIGHDESC, SCHOOLCODE, SCHOOLDESC, LEGAL1, LEGAL2, LEGAL3, TAXCODE, TAXDESC, TAXSUBCODE, TAXSUBCODE_DESC, OWNERCODE, OWNERDESC, CLASS, USECODE, USEDESC, LOTAREA, SALEDATE, SALEPRICE, SALECODE, SALEDESC, PREVSALEDATE, PREVSALEPRICE, PREVSALEDATE2, PREVSALEPRICE2, CHANGENOTICEADDRESS1, CHANGENOTICEADDRESS2, CHANGENOTICEADDRESS3, CHANGENOTICEADDRESS4, COUNTYBUILDING, COUNTYLAND, COUNTYTOTAL, COUNTYEXEMPTBLDG, LOCALBUILDING, LOCALLAND, LOCALTOTAL, FAIRMARKETBUILDING, FAIRMARKETLAND, FAIRMARKETTOTAL, STYLE, STYLEDESC, STORIES, YEARBLT, TOTALROOMS, BEDROOMS, FULLBATHS, HALFBATHS, GRADE, GRADEDESC, CONDITION, CONDITIONDESC, CDU, CDUDESC, TAXYEAR, GEO_MERGE_KEY, FEATURE_KE, ADDRESS_ID, PARENT_ID, STREET_ID, ADDRESS_TY, STATUS, ADDR_NUM_P, ADDR_NUM, ADDR_NUM_S, ST_PREMODI, ST_PREFIX, ST_PRETYPE, ST_NAME, ST_TYPE, ST_POSTMOD, UNIT_TYPE, UNIT, FLOOR, MUNICIPALI, COUNTY, STATE, ZIP_CODE, EDIT_DATE, EDIT_USER, SOURCE, EXP_FLAG, FULL_ADDRE, ST_SUFFIX, COMBINED_A, FULL_ADDR_, COMBINED_1, geometry]
Index: []

[0 rows x 96 columns]

#### Remaining duplicates

In [1952]:
# several of the 'duplicate' addresses still not matched
print(len(props_dupl_key[props_dupl_key.index.isin(not_merged.index)]))
props_dupl_key[props_dupl_key.index.isin(props_not_merged.index)].head(3)

19

,PROPERTYHOUSENUM,PROPERTYFRACTION,PROPERTYUNIT,PROPERTYADDRESS,PROPERTYCITY,PROPERTYSTATE,PROPERTYZIP,MUNICODE,MUNIDESC,NEIGHCODE,...,GRADE,GRADEDESC,CONDITION,CONDITIONDESC,CDU,CDUDESC,TAXYEAR,GEO_MERGE_KEY,MERGE_KEY_CITY,FULL_ADDRESS
PARID,,,,,,,,,,,,,,,,,,,,,
0168J00076000000,200,NaN,NaN,10TH ST,PITTSBURGH,PA,15215,852,Sharpsburg,55C52,...,NaN,NaN,<NA>,NaN,NaN,NaN,2026,200 10TH ST CITY OF PITTSBURGH 15215,CITY OF PITTSBURGH,200 10TH ST
0643B00174000000,382,NaN,NaN,WALL AVE,WILMERDING,PA,15148,861,Wall,86101,...,NaN,NaN,<NA>,NaN,NaN,NaN,2026,382 WALL AVE WILMERDING BOROUGH 15148,WILMERDING BOROUGH,382 WALL AVE
0643L00295000000,421,NaN,NaN,VALLEY AVE,WILMERDING,PA,15148,861,Wall,86101,...,NaN,NaN,<NA>,NaN,NaN,NaN,2026,421 VALLEY AVE WILMERDING BOROUGH 15148,WILMERDING BOROUGH,421 VALLEY AVE

In [1953]:
# some of these addresses are redundant and are already represented in the merged df
props_dupl_key.loc[:, 'FULL_ADDRESS'] = props_dupl_key[['PROPERTYHOUSENUM', 'PROPERTYFRACTION', 'PROPERTYADDRESS', 'PROPERTYUNIT']].fillna('').apply(combine_fields, axis=1)
props_dupl_key[props_dupl_key.index.isin(props_not_merged.index) & props_dupl_key['FULL_ADDRESS'].isin(props_geo['FULL_ADDRE'])]

,PROPERTYHOUSENUM,PROPERTYFRACTION,PROPERTYUNIT,PROPERTYADDRESS,PROPERTYCITY,PROPERTYSTATE,PROPERTYZIP,MUNICODE,MUNIDESC,NEIGHCODE,...,GRADE,GRADEDESC,CONDITION,CONDITIONDESC,CDU,CDUDESC,TAXYEAR,GEO_MERGE_KEY,MERGE_KEY_CITY,FULL_ADDRESS
PARID,,,,,,,,,,,,,,,,,,,,,
0168J00076000000,200,NaN,NaN,10TH ST,PITTSBURGH,PA,15215,852,Sharpsburg,55C52,...,NaN,NaN,<NA>,NaN,NaN,NaN,2026,200 10TH ST CITY OF PITTSBURGH 15215,CITY OF PITTSBURGH,200 10TH ST
0131A00236000000,322,NaN,NaN,CHERRY ST,HOMESTEAD,PA,15120,863,West Homestead,86302,...,D,BELOW AVERAGE,5,POOR,PR,POOR,2026,322 CHERRY ST HOMESTEAD BOROUGH 15120,HOMESTEAD BOROUGH,322 CHERRY ST
0167S00143000000,23,NaN,NaN,5TH ST,PITTSBURGH,PA,15215,852,Sharpsburg,85202,...,C-,AVERAGE -,3,AVERAGE,AV,AVERAGE,2026,23 5TH ST CITY OF PITTSBURGH 15215,CITY OF PITTSBURGH,23 5TH ST

In [1955]:
# ignore those addresses
props_not_merged = props_not_merged.drop(
    props_dupl_key[props_dupl_key.index.isin(props_not_merged.index) & props_dupl_key['FULL_ADDRESS'].isin(props_geo['FULL_ADDRE'])]\
        .index)

Will attempt to match remaining duplicates in same manner as other unmatched addresses first

### Additional matching

In [2327]:
def fuzzy_match_addr(left_df : pd.DataFrame, right_df : pd.DataFrame,
                     left_on = 'GEO_MERGE_KEY', right_on = 'GEO_MERGE_KEY',
                     left_zip = 'PROPERTYZIP', right_zip = 'ZIP_CODE', 
                     left_num = 'PROPERTYHOUSENUM', right_num = 'ADDR_NUM',
                     scorer = fuzz.WRatio, threshold = 0):
    
    results = []
    
    # limit comparisons to same zip and house number to avoid false matches (+ improve performance)
    for (zipcode, housenum), left_subset in left_df.groupby([left_zip, left_num]):
        subset_results = left_subset.copy()
        
        zipcode = int(zipcode)
        housenum = int(housenum)
        right_subset = right_df[
            (right_df[right_zip].astype(int) == zipcode) & 
            (right_df[right_num].astype(int) == housenum)
        ]
        
        # no matches
        if len(right_subset) == 0:
            continue
        
        left_vals = left_subset[left_on].values
        right_vals = right_subset[right_on].values
        
        # calculate fuzzy match matrix
        scores = process.cdist(
            left_vals,
            right_vals,
            scorer=scorer
        )
        
        match_idx = scores.argmax(axis=1)
        match_scores = scores.max(axis=1)
        
        subset_results['FUZZY_KEY'] = right_vals[match_idx]
        subset_results['FUZZY_SCORE'] = match_scores
        
        # drop results that did not meet threshold (0 in score matrix)
        subset_results.loc[subset_results['FUZZY_SCORE'] < threshold, 'FUZZY_KEY'] = None
        
        results.append(subset_results)
    
    return pd.concat(results)

#### Full address matches

Higher threshold, searching for near-exact matches on full address string ('fuzzy key')

In [ ]:
# manual testing on subset of data showed WRatio to be most consistently accurate scoring method
# setting threshold to 0 to include all results and allow manual filtering/postprocessing
# fuzzy_matched = fuzzy_match_addr(props_not_merged, address_points, scorer=fuzz.WRatio, threshold=0)

In [2145]:
fuzzy_matched[['GEO_MERGE_KEY', 'FUZZY_KEY', 'FUZZY_SCORE']].head()

,GEO_MERGE_KEY,FUZZY_KEY,FUZZY_SCORE
PARID,,,
0814D00173000000,25 MAIN ST 15003,25 MAIN ST BLDG A 15003,95.0
0933S00254000000,66 ORCHARD ST 15003,66 ORCHARD ST APT 1 15003,95.0
1061S00093000000,91 -93 LEWIS ST 15003,91 LEWIS ST 15003,95.0
0934N00251000000,128 MOUND ST 15003,128 MOUND ST APT 1 15003,95.0
0934N00178000000,171 MOUND ST 15003,171 MOUND ST APT 2 15003,95.0

In [2195]:
fuzzy_matched_succ = fuzzy_matched[fuzzy_matched['FUZZY_SCORE'] >= 95]
fuzzy_matched_succ = fuzzy_matched_succ\
    .reset_index()\
    .merge(
        address_points,
        how='inner',
        left_on='FUZZY_KEY',
        right_on='GEO_MERGE_KEY',
        suffixes=[None, '_y']
    )\
    .drop(columns='GEO_MERGE_KEY_y')\
    .set_index('PARID')
print(len(fuzzy_matched_succ))

12437

In [2197]:
fuzzy_matched_succ.head(3)

,PROPERTYHOUSENUM,PROPERTYFRACTION,PROPERTYUNIT,PROPERTYADDRESS,PROPERTYCITY,PROPERTYSTATE,PROPERTYZIP,MUNICODE,MUNIDESC,NEIGHCODE,...,EDIT_DATE,EDIT_USER,SOURCE,EXP_FLAG,FULL_ADDRE,ST_SUFFIX,COMBINED_A,FULL_ADDR_,COMBINED_1,geometry
PARID,,,,,,,,,,,,,,,,,,,,,
0814D00173000000,25,NaN,NaN,MAIN ST,AMBRIDGE,PA,15003,921,Leet,92103,...,2025-02-27,T096517,EAMS,None,25 MAIN ST BLDG A,None,25 MAIN ST BLDG A LEET TOWNSHIP 15003,25 MAIN ST,25 MAIN ST LEET TOWNSHIP 15003,POINT (1283097.6 463051.2)
0933S00254000000,66,NaN,NaN,ORCHARD ST,AMBRIDGE,PA,15003,921,Leet,92103,...,2023-05-04,T096517,EAMS,MPA,66 ORCHARD ST APT 1,None,66 ORCHARD ST APT 1 LEET TOWNSHIP 15003,66 ORCHARD ST,66 ORCHARD ST LEET TOWNSHIP 15003,POINT (1283274.987 463795.467)
1061S00093000000,91,-93,NaN,LEWIS ST,AMBRIDGE,PA,15003,883,Bell Acres,88303,...,2016-04-20,t096517,EAMS,None,91 LEWIS ST,None,91 LEWIS ST BELL ACRES BOROUGH 15003,91 LEWIS ST,91 LEWIS ST BELL ACRES BOROUGH 15003,POINT (1287568.9 466864.8)

In [2200]:
props_geo = pd.concat([props_geo, fuzzy_matched_succ])

In [2214]:
# update 'not merged' df
props_not_merged = props_not_merged[~props_not_merged.index.isin(props_geo.index)]
print(len(props_not_merged))

1227

#### Partial address matches

Matching with property unit and fraction fields ignored; this info may often be erroneous for mapping, and adds noise to fuzzy matching process

In [2241]:
props_not_merged.loc[:, 'PARTIAL_ADDRESS'] = props_not_merged[['PROPERTYHOUSENUM', 'PROPERTYADDRESS', 'PROPERTYZIP']].apply(combine_fields, axis=1)

In [2242]:
props_not_merged.iloc[:, -2:].head()

,GEO_MERGE_KEY,PARTIAL_ADDRESS
PARID,,
0001G00080000001,111 BOULEVARD OF THE ALLIES 15222,111 BOULEVARD OF THE ALLIES 15222
0001G00109000000,100 MARKET ST 15222,100 MARKET ST 15222
0001H00181000400,223 4TH AVE UNIT 400 15222,223 4TH AVE 15222
0001H00181000500,223 4TH AVE UNIT 500 15222,223 4TH AVE 15222
0001H00181000700,223 4TH AVE UNIT 700 15222,223 4TH AVE 15222

In [2346]:
# token_set_ratio appears to perform better than WRatio in this case (based on manual review of random samples)
fuzzy_matched_partial = fuzzy_match_addr(props_not_merged, address_points, left_on='PARTIAL_ADDRESS', scorer=fuzz.token_set_ratio, threshold=0)

In [2348]:
fuzzy_matched_partial[['GEO_MERGE_KEY', 'PARTIAL_ADDRESS', 'FUZZY_KEY', 'FUZZY_SCORE']].head()

,GEO_MERGE_KEY,PARTIAL_ADDRESS,FUZZY_KEY,FUZZY_SCORE
PARID,,,,
8000T00941000000,761 BIG SEWICKLEY CREEK RD 15003,761 BIG SEWICKLEY CREEK RD 15003,761 AMBRIDGE AVE 15003,59.259258
2179A00112000000,310 AMARYLLIS LN 15005,310 AMARYLLIS LN 15005,310 AZALEA LN 15005,78.048782
1224K00156000000,835 1ST AVE 15014,835 1ST AVE 15014,835 6TH AVE 15014,88.235291
1224B00323000000,943 CLEVELAND AVE 15014,943 CLEVELAND AVE 15014,943 8TH AVE 15014,86.666664
1367N00240000000,954 -960 RESERVOIR DR 15014,954 RESERVOIR DR 15014,954 ROUP AVE 15014,66.666664

In [2385]:
# edge cases: matching appears consistently successful until below score 92
# (first noticeable error is 551 PINE AVE -> 551 PRICE AVE)
fuzzy_matched_partial[(fuzzy_matched_partial['FUZZY_SCORE'] > 91.85) & (fuzzy_matched_partial['FUZZY_SCORE'] < 92.25)]\
    .sort_values('FUZZY_SCORE', ascending=False)\
    .iloc[:, -4:]

,GEO_MERGE_KEY,PARTIAL_ADDRESS,FUZZY_KEY,FUZZY_SCORE
PARID,,,,
0011J00225000000,1915 BOULEVARD OF THE ALLIES 15219,1915 BOULEVARD OF THE ALLIES 15219,1915 BLVD OF THE ALLIES 15219,92.063492
0174L00201000000,7601 FRANKSTOWN WAY 15208,7601 FRANKSTOWN WAY 15208,7601 FRANKSTOWN AVE 15208,92.000000
1508L00010000000,1605 MIDDLE RD 15044,1605 MIDDLE RD 15044,1605 MIDDLE ROAD EXT 15044,91.891891
0237C00059000000,551 PINE AVE 15104,551 PINE AVE 15104,551 PRICE AVE 15104,91.891891
0011J00039000000,1911 WATSON AVE 15219,1911 WATSON AVE 15219,1911 WATSON ST 15219,91.891891
0002M00205000A00,1621 FORBES ST 15219,1621 FORBES ST 15219,1621 FORBES AVE 15219,91.891891
0178K00025000000,7217 SCHLEY AVE 15218,7217 SCHLEY AVE 15218,7217 SCHLEY CT 15218,91.891891
0225S00310000000,1 MEADOWOOD DR 15215,1 MEADOWOOD DR 15215,1 MEADOWOOD CT 15215,91.891891
0055J00111000000,4301 IRVINE AVE 15207,4301 IRVINE AVE 15207,4301 IRVINE ST 15207,91.891891
0055A00317000000,150 -180 BIGELOW SPUR 15207,150 BIGELOW SPUR 15207,150 BIGELOW ST 15207,91.891891
0050S00284000000,117 S AIKEN ST 15206,117 S AIKEN ST 15206,117 S AIKEN AVE 15206,91.891891
0545S00050000000,113 WATKINS ST 15148,113 WATKINS ST 15148,113 WATKINS AVE 15148,91.891891
0446A00278000000,310 5TH ST EXT 15147,310 5TH ST EXT 15147,310 5TH STREET EXT 15147,91.891891
0043B00133000000,200 BRADLEY AVE 15136,200 BRADLEY AVE 15136,200 BRADLEY ST 15136,91.891891
0460R00248000000,806 VERMONT ST 15131,806 VERMONT ST 15131,806 VERMONT AVE 15131,91.891891
0067J00100000000,54 ARCH ST EXT 15106,54 ARCH ST EXT 15106,54 ARCH STREET EXT 15106,91.891891
0301A00006000000,1024 MORGAN LN 15104,1024 MORGAN LN 15104,1024 MORGAN WAY 15104,91.891891
0020A00096000000,286 -300 CORLISS AVE 15220,286 CORLISS AVE 15220,286 CORLISS ST 15220,91.891891

In [2365]:
fuzzy_matched_partial_succ = fuzzy_matched_partial[fuzzy_matched_partial['FUZZY_SCORE'] >= 92]
fuzzy_matched_partial_succ = fuzzy_matched_partial_succ\
    .reset_index()\
    .merge(
        address_points,
        how='inner',
        left_on='FUZZY_KEY',
        right_on='GEO_MERGE_KEY',
        suffixes=[None, '_y']
    )\
    .drop(columns='GEO_MERGE_KEY_y')\
    .set_index('PARID')
print(len(fuzzy_matched_partial_succ))

566

In [2367]:
props_geo = pd.concat([props_geo, fuzzy_matched_partial_succ])

In [2369]:
props_geo.tail(1)

,PROPERTYHOUSENUM,PROPERTYFRACTION,PROPERTYUNIT,PROPERTYADDRESS,PROPERTYCITY,PROPERTYSTATE,PROPERTYZIP,MUNICODE,MUNIDESC,NEIGHCODE,...,EXP_FLAG,FULL_ADDRE,ST_SUFFIX,COMBINED_A,FULL_ADDR_,COMBINED_1,geometry,FUZZY_KEY,FUZZY_SCORE,PARTIAL_ADDRESS
0319D00175000000,1630,NaN,NaN,N HIGHLAND RD,PITTSBURGH,PA,15241,950,Upper St. Clair,95004,...,None,1630 N HIGHLAND RD,None,1630 N HIGHLAND RD UPPER SAINT CLAIR TOWNSHIP ...,1630 N HIGHLAND RD,1630 N HIGHLAND RD UPPER SAINT CLAIR TOWNSHIP ...,POINT (1326993.7 379785.3),1630 N HIGHLAND RD 15241,100.0,1630 N HIGHLAND RD 15241

In [2370]:
# update 'not merged' df
props_not_merged = props_not_merged[~props_not_merged.index.isin(props_geo.index)]
print(len(props_not_merged))

661

### External geocoding

Remaining ummatched addresses can be matched by geocoding API

In [ ]:
props_not_merged.to_csv('data/processing/prop_subset_toGeocode.csv')

In [ ]:
# import processed results
props_not_merged_geo = geopandas.read_file('data/processing/prop_subset_geocoded.geojson')
props_not_merged_geo = props_not_merged_geo.set_index('PARID')
props_not_merged_geo = props_not_merged_geo.to_crs(address_points.crs)

In [2399]:
props_not_merged_geo.head(1)

,PROPERTYHOUSENUM,PROPERTYFRACTION,PROPERTYUNIT,PROPERTYADDRESS,PROPERTYCITY,PROPERTYSTATE,PROPERTYZIP,MUNICODE,MUNIDESC,NEIGHCODE,...,GRADE,GRADEDESC,CONDITION,CONDITIONDESC,CDU,CDUDESC,TAXYEAR,GEO_MERGE_KEY,PARTIAL_ADDRESS,geometry
PARID,,,,,,,,,,,,,,,,,,,,,
0002H00033000000,1516,None,None,5TH AVE,PITTSBURGH,PA,15219,101,1st Ward - PITTSBURGH,51C04,...,None,None,NaN,None,None,None,2026,1516 5TH AVE 15219,1516 5TH AVE 15219,POINT (1346591.885 410392.152)

In [2402]:
props_geo = pd.concat([props_geo, props_not_merged_geo])

In [2404]:
props_not_merged = props_not_merged[~props_not_merged.index.isin(props_geo.index)]
print(len(props_not_merged))

0

In [ ]:
# every mappable address has been geocoded :D
props_geo[props_geo['geometry'].isna()]

Empty DataFrame
Columns: [PROPERTYHOUSENUM, PROPERTYFRACTION, PROPERTYUNIT, PROPERTYADDRESS, PROPERTYCITY, PROPERTYSTATE, PROPERTYZIP, MUNICODE, MUNIDESC, NEIGHCODE, NEIGHDESC, SCHOOLCODE, SCHOOLDESC, LEGAL1, LEGAL2, LEGAL3, TAXCODE, TAXDESC, TAXSUBCODE, TAXSUBCODE_DESC, OWNERCODE, OWNERDESC, CLASS, USECODE, USEDESC, LOTAREA, SALEDATE, SALEPRICE, SALECODE, SALEDESC, PREVSALEDATE, PREVSALEPRICE, PREVSALEDATE2, PREVSALEPRICE2, CHANGENOTICEADDRESS1, CHANGENOTICEADDRESS2, CHANGENOTICEADDRESS3, CHANGENOTICEADDRESS4, COUNTYBUILDING, COUNTYLAND, COUNTYTOTAL, COUNTYEXEMPTBLDG, LOCALBUILDING, LOCALLAND, LOCALTOTAL, FAIRMARKETBUILDING, FAIRMARKETLAND, FAIRMARKETTOTAL, STYLE, STYLEDESC, STORIES, YEARBLT, TOTALROOMS, BEDROOMS, FULLBATHS, HALFBATHS, GRADE, GRADEDESC, CONDITION, CONDITIONDESC, CDU, CDUDESC, TAXYEAR, GEO_MERGE_KEY, FEATURE_KE, ADDRESS_ID, PARENT_ID, STREET_ID, ADDRESS_TY, STATUS, ADDR_NUM_P, ADDR_NUM, ADDR_NUM_S, ST_PREMODI, ST_PREFIX, ST_PRETYPE, ST_NAME, ST_TYPE, ST_POSTMOD, UNIT_TYPE, UNIT, FLOOR, MUNICIPALI, COUNTY, STATE, ZIP_CODE, EDIT_DATE, EDIT_USER, SOURCE, EXP_FLAG, FULL_ADDRE, ST_SUFFIX, COMBINED_A, FULL_ADDR_, COMBINED_1, geometry, FUZZY_KEY, FUZZY_SCORE, PARTIAL_ADDRESS]
Index: []

[0 rows x 99 columns]

### Owner addresses

#### Cleaning/Consolidating

In [3300]:
# clean owner address cols
props_geo.loc[props_geo['CHANGENOTICEADDRESS1'].notna(), 'CHANGENOTICEADDRESS1'] = props_geo['CHANGENOTICEADDRESS1'].dropna().apply(lambda x: re.sub(r'\s+', ' ', re.sub(r'[^\s\w#]' , '', str(x).upper())))
props_geo.loc[props_geo['CHANGENOTICEADDRESS3'].notna(), 'CHANGENOTICEADDRESS3'] = props_geo['CHANGENOTICEADDRESS3'].dropna().apply(lambda x: re.sub(r'\s+', ' ', re.sub(r'[^\s\w]' , '', str(x).upper())))
props_geo.loc[props_geo['CHANGENOTICEADDRESS4'].notna(), 'CHANGENOTICEADDRESS4'] = props_geo['CHANGENOTICEADDRESS4'].dropna().apply(lambda x: re.sub(r'\.\d+' , '', str(x).upper()))

In [3301]:
# create combined address field
props_geo.loc[:, 'OWNERADDR_COMBINED'] = props_geo[['CHANGENOTICEADDRESS1', 'CHANGENOTICEADDRESS3', 'CHANGENOTICEADDRESS4']].fillna('').apply(combine_fields, axis=1)

In [3302]:
# remove extra symbols from combined address
props_geo.loc[:, 'OWNERADDR_COMBINED'] = props_geo['OWNERADDR_COMBINED'].apply(lambda x: re.sub(r'\s+', ' ', re.sub(r'[^\s\w]' , '', str(x))))

In [3303]:
# replace empty strings with nan
props_geo.loc[props_geo['OWNERADDR_COMBINED'] == '', 'OWNERADDR_COMBINED'] = np.nan

In [3304]:
props_geo['OWNERADDR_COMBINED'].head()

0001C00167000000     7044 SEPULVEDA BLVD 1333 VAN NUYS CA
0001C00200000001                345 6TH AVE PITTSBURGH PA
0001C00228000100     11 PARKWAY CTR STE 300 PITTSBURGH PA
0001G00224050600               23 TOWER LN MONONGAHELA PA
0001G00224060100    2255 CONSTITUTION BLVD MC KEESPORT PA
Name: OWNERADDR_COMBINED, dtype: object

In [3305]:
# block fuzzy string matching in consolidate_names() by numeric info from first address field (house num, unit num, PO box, etc.)
# to limit incorrect conversions + improve performance
# (may miss some genuine misinputs of numbers, but these are difficult to differentiate from distinct but similar numbers)
owneraddr_block = pd.DataFrame({'key' : props_geo['CHANGENOTICEADDRESS1'].apply(lambda x: ' '.join(re.findall(r'\d+', str(x))))})

In [3306]:
owneraddr_block['key'].value_counts()

key
111       1622
110       1609
105       1584
104       1561
108       1545
          ...
820 13       1
881 13       1
555 4        1
808 10       1
12748        1
Name: count, Length: 30149, dtype: int64

In [3307]:
# consolidate with fuzzy string matching
owneraddr_consol = consolidate_names(props_geo, 'OWNERADDR_COMBINED', block_by=owneraddr_block, threshold=98, scorer=fuzz.WRatio)

In [3308]:
props_geo.loc[:, 'OWNERADDR_CLEAN'] = owneraddr_consol[0]

In [3309]:
# converted addresses
props_geo.loc[props_geo['OWNERADDR_COMBINED'] != props_geo['OWNERADDR_CLEAN'], ['OWNERADDR_COMBINED', 'OWNERADDR_CLEAN']].drop_duplicates().dropna()

,OWNERADDR_COMBINED,OWNERADDR_CLEAN
0001H00061000000,315 PAYDAYS DR ELIZABETH PA,315 PAYDAY DR ELIZABETH PA
0002G00022000000,5020 THOMAS RUN RD OAKDALE PA,5020 THOMS RUN RD OAKDALE PA
0011J00288000000,1811 BOULEVARD OF THE ALLLIES PITTSBURGH PA,1811 BOULEVARD OF THE ALLIES PITTSBURGH PA
0025K00162041800,320 FT DUQUESNE BLVD UNIT 11C PITTSBURGH PA,320 FT DUQUESNE BLVD UNIT 11 C PITTSBURGH PA
0002F00175015800,112 WASHINGTON PL UNIT 15HJ PITTSBURGH PA,112 WASHINGTON PL UNIT 15H PITTSBURGH PA
...,...,...
0006M00312181000,P O BOX 10234 PITTSBURGH PA,PO BOX 10234 PITTSBURGH PA
0006M00312486000,1 TRIMONT LN UNIT 870 D PITTSBURGH PA,1 TRIMONT LN UNIT 870D PITTSBURGH PA
0167S00185000000,1124 DE VICTOR PL PITTSBURGH PA,1124 DEVICTOR PL PITTSBURGH PA
0747B00319000000,150 LEYROY ST PITTSBURGH PA,150 LEROY ST PITTSBURGH PA
0043B00133000000,200 BRADLY ST MC KEES ROCKS PA,200 BRADLEY ST MC KEES ROCKS PA

In [3310]:
props_geo['OWNERADDR_CLEAN'].value_counts()[:10]

OWNERADDR_CLEAN
414 GRANT ST RM 200 PITTSBURGH PA            819
PO BOX 4900 SCOTTSDALE AZ                    432
412 BLVD OF THE ALLIES FL 7 PITTSBURGH PA    418
829 INDUSTRY ST PITTSBURGH PA                399
901 BINGHAM ST PITTSBURGH PA                 341
3500 PARK CENTER DR STE 100 DAYTON OH        304
375 GOLFSIDE DR WEXFORD PA                   295
310 SEVEN FIELDS BLVD STE 350 MARS PA        277
301 CHARTIERS AVE MC KEES ROCKS PA           204
1812 E CARSON ST PITTSBURGH PA               189
Name: count, dtype: int64

#### Encoding

##### Property owners table

In [3311]:
# new df from unique canonical addresses
prop_owners = props_geo[props_geo['OWNERADDR_CLEAN'] == props_geo['OWNERADDR_COMBINED']]\
    .reset_index()\
    .loc[:, ['OWNERADDR_CLEAN', 'CHANGENOTICEADDRESS1', 'CHANGENOTICEADDRESS3', 'CHANGENOTICEADDRESS4']]\
    .drop_duplicates('OWNERADDR_CLEAN')
prop_owners.columns = ['OWNER_CLEANADDR', 'OWNER_STREETADDR', 'OWNER_PLACE', 'OWNER_ZIP']
prop_owners.head()

,OWNER_CLEANADDR,OWNER_STREETADDR,OWNER_PLACE,OWNER_ZIP
0,7044 SEPULVEDA BLVD 1333 VAN NUYS CA,7044 SEPULVEDA BLVD # 1333,VAN NUYS CA,NaN
1,345 6TH AVE PITTSBURGH PA,345 6TH AVE,PITTSBURGH PA,NaN
2,11 PARKWAY CTR STE 300 PITTSBURGH PA,11 PARKWAY CTR STE 300,PITTSBURGH PA,NaN
3,23 TOWER LN MONONGAHELA PA,23 TOWER LN,MONONGAHELA PA,NaN
4,2255 CONSTITUTION BLVD MC KEESPORT PA,2255 CONSTITUTION BLVD,MC KEESPORT PA,NaN

In [3312]:
# generate ids
rng = np.random.default_rng(82)
prop_owners['OWNER_ID'] = rng.integers(1e11, 1e12, len(prop_owners))
prop_owners = prop_owners.set_index('OWNER_ID')

In [3313]:
prop_owners['OWNER_STATE'] = prop_owners['OWNER_PLACE'].str.extract(r'\s+(\w{2})$')

In [3314]:
prop_owners['OWNER_CITY'] = prop_owners['OWNER_PLACE'].str.replace(r'\s+\w{2}$', '', regex=True)

In [3315]:
print(len(prop_owners))
prop_owners.head()

394841

,OWNER_CLEANADDR,OWNER_STREETADDR,OWNER_PLACE,OWNER_ZIP,OWNER_STATE,OWNER_CITY
OWNER_ID,,,,,,
997874877146,7044 SEPULVEDA BLVD 1333 VAN NUYS CA,7044 SEPULVEDA BLVD # 1333,VAN NUYS CA,NaN,CA,VAN NUYS
869309154033,345 6TH AVE PITTSBURGH PA,345 6TH AVE,PITTSBURGH PA,NaN,PA,PITTSBURGH
295917759402,11 PARKWAY CTR STE 300 PITTSBURGH PA,11 PARKWAY CTR STE 300,PITTSBURGH PA,NaN,PA,PITTSBURGH
982130871663,23 TOWER LN MONONGAHELA PA,23 TOWER LN,MONONGAHELA PA,NaN,PA,MONONGAHELA
467730082437,2255 CONSTITUTION BLVD MC KEESPORT PA,2255 CONSTITUTION BLVD,MC KEESPORT PA,NaN,PA,MC KEESPORT

In [3316]:
# map addresses to index of owner df
props_geo['OWNER_ID'] = props_geo['OWNERADDR_CLEAN'].map(prop_owners.reset_index().set_index('OWNER_CLEANADDR')['OWNER_ID'].to_dict())

In [3317]:
props_geo[['OWNERADDR_CLEAN', 'OWNER_ID']].head()

                                        OWNERADDR_CLEAN      OWNER_ID
0001C00167000000   7044 SEPULVEDA BLVD 1333 VAN NUYS CA  9.978749e+11
0001C00200000001              345 6TH AVE PITTSBURGH PA  8.693092e+11
0001C00228000100   11 PARKWAY CTR STE 300 PITTSBURGH PA  2.959178e+11
0001G00224050600             23 TOWER LN MONONGAHELA PA  9.821309e+11
0001G00224060100  2255 CONSTITUTION BLVD MC KEESPORT PA  4.677301e+11

In [3537]:
props_geo['OWNER_ID'].value_counts().head(1000)

OWNER_ID
6.295600e+11    819
3.775686e+11    432
2.694809e+11    418
2.506849e+11    399
3.351094e+11    341
               ...
1.912159e+11     12
4.579732e+11     12
9.909886e+11     12
4.223306e+11     12
8.252891e+11     12
Name: count, Length: 1000, dtype: int64

In [3517]:
prop_owners['PROP_COUNT'] = props_geo['OWNER_ID'].value_counts()

##### ~~Cleaning/filtering municipalities~~

In [ ]:
pa_munis = pd.read_csv('data/processing/pa_municipalities.csv')
pa_munis['IN_ALLEGHENY'] = (pa_munis['COUNTY1'] == 'ALLEGHENY') | (pa_munis['COUNTY2'] == 'ALLEGHENY')
pa_munis.head()

   MUNICIPALITY  TYPE       COUNTY1 COUNTY2  IN_ALLEGHENY
0  PHILADELPHIA  CITY  PHILADELPHIA     NaN         False
1    PITTSBURGH  CITY     ALLEGHENY     NaN          True
2     ALLENTOWN  CITY        LEHIGH     NaN         False
3       READING  CITY         BERKS     NaN         False
4          ERIE  CITY          ERIE     NaN         False

In [3442]:
pa_munis[pa_munis['IN_ALLEGHENY'] & pa_munis['MUNICIPALITY'].duplicated(keep=False)]

     MUNICIPALITY            TYPE    COUNTY1 COUNTY2  IN_ALLEGHENY
36           ROSS        TOWNSHIP  ALLEGHENY     NaN          True
48           PLUM         BOROUGH  ALLEGHENY     NaN          True
89        BALDWIN         BOROUGH  ALLEGHENY     NaN          True
121         SCOTT        TOWNSHIP  ALLEGHENY     NaN          True
167     WHITEHALL         BOROUGH  ALLEGHENY     NaN          True
176      ROBINSON        TOWNSHIP  ALLEGHENY     NaN          True
179     ELIZABETH        TOWNSHIP  ALLEGHENY     NaN          True
201          PINE        TOWNSHIP  ALLEGHENY     NaN          True
213      RICHLAND        TOWNSHIP  ALLEGHENY     NaN          True
240      HARRISON        TOWNSHIP  ALLEGHENY     NaN          True
377       INDIANA        TOWNSHIP  ALLEGHENY     NaN          True
748     SEWICKLEY         BOROUGH  ALLEGHENY     NaN          True
825    SPRINGDALE         BOROUGH  ALLEGHENY     NaN          True
830       FORWARD        TOWNSHIP  ALLEGHENY     NaN          True
1033      LIBERTY         BOROUGH  ALLEGHENY     NaN          True
1103         FAWN        TOWNSHIP  ALLEGHENY     NaN          True
1242      BALDWIN        TOWNSHIP  ALLEGHENY     NaN          True
1279       ALEPPO        TOWNSHIP  ALLEGHENY     NaN          True
1401   SPRINGDALE        TOWNSHIP  ALLEGHENY     NaN          True
1484    ELIZABETH         BOROUGH  ALLEGHENY     NaN          True
1630   HEIDELBERG         BOROUGH  ALLEGHENY     NaN          True
1743      LINCOLN         BOROUGH  ALLEGHENY     NaN          True
2563      CLINTON             CDP  ALLEGHENY     NaN          True
2574     INDUSTRY             CDP  ALLEGHENY     NaN          True
2597        KARNS  UNINCORPORATED  ALLEGHENY     NaN          True
2601       MORGAN  UNINCORPORATED  ALLEGHENY     NaN          True

In [3427]:
allegheny_munis = np.array(pa_munis.loc[pa_munis['IN_ALLEGHENY'], 'MUNICIPALITY'])

In [3318]:
def fuzzy_match_name(col : pd.Series, search_space, scorer = fuzz.WRatio, threshold = 0):    
    # order by most frequent
    uniques = col.value_counts().index
    choices = np.array(search_space)
    results = pd.DataFrame(columns=['NAME', 'MATCH', 'SCORE']).set_index('NAME')
    
    for name in uniques:
        match = process.extractOne(
            name,
            choices,
            scorer=scorer
        )
        
        match_name = match[0]
        match_score = match[1]
        
        if match_score >= threshold:
            results.loc[name, 'MATCH'] = match_name
            results.loc[name, 'SCORE'] = match_score
        # else:
        #     results.loc[name] = None
    
    return results

In [ ]:
# only consider places confirmed in PA or without confirmed state (also ignore those with null address, e.g. only country)
owner_place_candidates = prop_owners.loc[(prop_owners['OWNER_STATE'] == 'PA') | \
    (prop_owners['OWNER_STATE'].isna()) & \
    (prop_owners['OWNER_STREETADDR'].notna())]

In [3448]:
# ignore places confirmed outside allegheny county
# NOTE: pay attention to duplicate muni names
# owner_place_candidates[(owner_place_candidates['OWNER_CITY'].isin(pa_munis['MUNICIPALITY'])) & \
#     (owner_place_candidates['OWNER_CITY'].isin(pa_munis.loc[~pa_munis['IN_ALLEGHENY'], 'MUNICIPALITY']))]

In [3447]:
owner_place_candidates.head()

,OWNER_CLEANADDR,OWNER_STREETADDR,OWNER_PLACE,OWNER_ZIP,OWNER_STATE,OWNER_CITY
OWNER_ID,,,,,,
869309154033,345 6TH AVE PITTSBURGH PA,345 6TH AVE,PITTSBURGH PA,NaN,PA,PITTSBURGH
295917759402,11 PARKWAY CTR STE 300 PITTSBURGH PA,11 PARKWAY CTR STE 300,PITTSBURGH PA,NaN,PA,PITTSBURGH
982130871663,23 TOWER LN MONONGAHELA PA,23 TOWER LN,MONONGAHELA PA,NaN,PA,MONONGAHELA
467730082437,2255 CONSTITUTION BLVD MC KEESPORT PA,2255 CONSTITUTION BLVD,MC KEESPORT PA,NaN,PA,MC KEESPORT
945164723357,151 FORT PITT BLVD UNIT 602 PITTSBURGH PA,151 FORT PITT BLVD UNIT 602,PITTSBURGH PA,NaN,PA,PITTSBURGH

In [3380]:
owner_place_results_a = fuzzy_match_name(owner_place_candidates['OWNER_CITY'], allegheny_munis['MUNICIPALITY'])

In [ ]:
owner_place_results_a[(owner_place_results_a['SCORE'] >= 90) & (owner_place_results_a['SCORE'] < 100)].sort_values('SCORE')

#### Geocoding

In [ ]:
# TODO: geocode top ~1000 owner addresses?
    # limit to just those in allegheny county (try matching '___ PA' to list of municipalities)
    # can potentially use Places API to associate with actual businesses
    # try matching to address points dataset first but results might be limited(?)

In [3538]:
# top 1000 most common owners
prop_owners_top = prop_owners.loc[props_geo['OWNER_ID'].value_counts().index].head(1000)
prop_owners_top

,OWNER_CLEANADDR,OWNER_STREETADDR,OWNER_PLACE,OWNER_ZIP,OWNER_STATE,OWNER_CITY,PROP_COUNT
OWNER_ID,,,,,,,
629560013250,414 GRANT ST RM 200 PITTSBURGH PA,414 GRANT ST RM 200,PITTSBURGH PA,NaN,PA,PITTSBURGH,819
377568607449,PO BOX 4900 SCOTTSDALE AZ,PO BOX 4900,SCOTTSDALE AZ,NaN,AZ,SCOTTSDALE,432
269480886837,412 BLVD OF THE ALLIES FL 7 PITTSBURGH PA,412 BLVD OF THE ALLIES FL 7,PITTSBURGH PA,NaN,PA,PITTSBURGH,418
250684894979,829 INDUSTRY ST PITTSBURGH PA,829 INDUSTRY ST,PITTSBURGH PA,NaN,PA,PITTSBURGH,399
335109363737,901 BINGHAM ST PITTSBURGH PA,901 BINGHAM ST,PITTSBURGH PA,NaN,PA,PITTSBURGH,341
...,...,...,...,...,...,...,...
191215870994,2071 ARDMORE BLVD PITTSBURGH PA,2071 ARDMORE BLVD,PITTSBURGH PA,NaN,PA,PITTSBURGH,12
457973174273,211 BLOSSOM CT NEW KENSINGTON PA,211 BLOSSOM CT,NEW KENSINGTON PA,NaN,PA,NEW KENSINGTON,12
990988592252,1002 KING EDWARD DR MC DONALD PA,1002 KING EDWARD DR,MC DONALD PA,NaN,PA,MC DONALD,12
422330616417,5374 WILLIAM FLYNN HWY GIBSONIA PA,5374 WILLIAM FLYNN HWY,GIBSONIA PA,NaN,PA,GIBSONIA,12
825289090756,187 ROBINSON RD IMPERIAL PA,187 ROBINSON RD,IMPERIAL PA,NaN,PA,IMPERIAL,12

In [3539]:
prop_owners_top.to_csv('data/processing/prop_owners_top.csv')

In [3540]:
prop_owners_top_geo = geopandas.read_file('data/processing/prop_owners_top_geocoded.geojson')
prop_owners_top_geo = prop_owners_top_geo.set_index('OWNER_ID')
prop_owners_top_geo = prop_owners_top_geo.to_crs(address_points.crs)

In [3548]:
prop_owners_top_geo.head(1)

,OWNER_CLEANADDR,OWNER_STREETADDR,OWNER_PLACE,OWNER_ZIP,OWNER_STATE,OWNER_CITY,geometry,PROP_COUNT
OWNER_ID,,,,,,,,
629560013250,414 GRANT ST RM 200 PITTSBURGH PA,414 GRANT ST RM 200,PITTSBURGH PA,NaN,PA,PITTSBURGH,POINT (1343063.002 410457.225),819

## Exporting

In [ ]:
# cache finalized dataframes
with shelve.open('cache/process_properties') as cache:
    cache['props_geo'] = props_geo
    cache['prop_owners'] = prop_owners
    cache['prop_owners_top_geo'] = prop_owners_top_geo

In [ ]:
# pull from cache
# with shelve.open('cache/process_properties') as cache:
#     props_geo = cache['props_geo']
#     prop_owners = cache['prop_owners']
#     prop_owners_top_geo = cache['prop_owners_top_geo']

In [4]:
prop_owners_top_geo.to_file('data/final/PropertyOwners_geo.shp.zip')

/var/folders/zj/02jlcxcn1dz5jm6ct_f_4wrr0000gn/T/ipykernel_50623/13654442.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  prop_owners_top_geo.to_file('data/final/PropertyOwners_geo.shp.zip')
/opt/anaconda3/envs/dsa_py/lib/python3.13/site-packages/pyogrio/raw.py:723: RuntimeWarning: Normalized/laundered field name: 'OWNER_CLEANADDR' to 'OWNER_CLEA'
  ogr_write(
/opt/anaconda3/envs/dsa_py/lib/python3.13/site-packages/pyogrio/raw.py:723: RuntimeWarning: Normalized/laundered field name: 'OWNER_STREETADDR' to 'OWNER_STRE'
  ogr_write(
/opt/anaconda3/envs/dsa_py/lib/python3.13/site-packages/pyogrio/raw.py:723: RuntimeWarning: Normalized/laundered field name: 'OWNER_PLACE' to 'OWNER_PLAC'
  ogr_write(
/opt/anaconda3/envs/dsa_py/lib/python3.13/site-packages/pyogrio/raw.py:723: RuntimeWarning: Normalized/laundered field name: 'OWNER_STATE' to 'OWNER_STAT'
  ogr_write(

In [2411]:
props_geo = geopandas.GeoDataFrame(props_geo)

In [7]:
list(props_geo.columns)

['PROPERTYHOUSENUM',
 'PROPERTYFRACTION',
 'PROPERTYUNIT',
 'PROPERTYADDRESS',
 'PROPERTYCITY',
 'PROPERTYSTATE',
 'PROPERTYZIP',
 'MUNICODE',
 'MUNIDESC',
 'NEIGHCODE',
 'NEIGHDESC',
 'SCHOOLCODE',
 'SCHOOLDESC',
 'LEGAL1',
 'LEGAL2',
 'LEGAL3',
 'TAXCODE',
 'TAXDESC',
 'TAXSUBCODE',
 'TAXSUBCODE_DESC',
 'OWNERCODE',
 'OWNERDESC',
 'CLASS',
 'USECODE',
 'USEDESC',
 'LOTAREA',
 'SALEDATE',
 'SALEPRICE',
 'SALECODE',
 'SALEDESC',
 'PREVSALEDATE',
 'PREVSALEPRICE',
 'PREVSALEDATE2',
 'PREVSALEPRICE2',
 'CHANGENOTICEADDRESS1',
 'CHANGENOTICEADDRESS2',
 'CHANGENOTICEADDRESS3',
 'CHANGENOTICEADDRESS4',
 'COUNTYBUILDING',
 'COUNTYLAND',
 'COUNTYTOTAL',
 'COUNTYEXEMPTBLDG',
 'LOCALBUILDING',
 'LOCALLAND',
 'LOCALTOTAL',
 'FAIRMARKETBUILDING',
 'FAIRMARKETLAND',
 'FAIRMARKETTOTAL',
 'STYLE',
 'STYLEDESC',
 'STORIES',
 'YEARBLT',
 'TOTALROOMS',
 'BEDROOMS',
 'FULLBATHS',
 'HALFBATHS',
 'GRADE',
 'GRADEDESC',
 'CONDITION',
 'CONDITIONDESC',
 'CDU',
 'CDUDESC',
 'TAXYEAR',
 'GEO_MERGE_KEY',
 'FEATURE_KE',
 'ADDRESS_ID',
 'PARENT_ID',
 'STREET_ID',
 'ADDRESS_TY',
 'STATUS',
 'ADDR_NUM_P',
 'ADDR_NUM',
 'ADDR_NUM_S',
 'ST_PREMODI',
 'ST_PREFIX',
 'ST_PRETYPE',
 'ST_NAME',
 'ST_TYPE',
 'ST_POSTMOD',
 'UNIT_TYPE',
 'UNIT',
 'FLOOR',
 'MUNICIPALI',
 'COUNTY',
 'STATE',
 'ZIP_CODE',
 'EDIT_DATE',
 'EDIT_USER',
 'SOURCE',
 'EXP_FLAG',
 'FULL_ADDRE',
 'ST_SUFFIX',
 'COMBINED_A',
 'FULL_ADDR_',
 'COMBINED_1',
 'geometry',
 'FUZZY_KEY',
 'FUZZY_SCORE',
 'PARTIAL_ADDRESS',
 'OWNERADDR_COMBINED',
 'OWNERADDR_CLEAN',
 'OWNER_ID']

In [ ]:
export_columns = ['geometry', 'GEO_MERGE_KEY', 'FUZZY_KEY', 'FULL_ADDRE',
                  'PROPERTYHOUSENUM', 'PROPERTYFRACTION', 'PROPERTYUNIT', 'PROPERTYADDRESS', 'PROPERTYCITY', 'PROPERTYZIP', 
                  'MUNIDESC', 'NEIGHDESC', 
                  'TAXCODE', 'OWNER_ID', 'OWNERDESC',
                #   'CLASSDESC', 
                  'CLASS', 'USEDESC',
                  'FAIRMARKETTOTAL', 'SALEDATE', 'SALEPRICE', 'PREVSALEDATE', 'PREVSALEPRICE', 'PREVSALEDATE2', 'PREVSALEPRICE2',
                  'STYLEDESC', 'YEARBLT', 'LOTAREA', 'STORIES', 'TOTALROOMS', 'GRADE', 'CONDITION', 'CDUDESC']
props_export = props_geo[export_columns]

In [3680]:
props_export.head(1)

,geometry,GEO_MERGE_KEY,FUZZY_KEY,FULL_ADDRE,PROPERTYHOUSENUM,PROPERTYFRACTION,PROPERTYUNIT,PROPERTYADDRESS,PROPERTYCITY,PROPERTYZIP,...,PREVSALEDATE2,PREVSALEPRICE2,STYLEDESC,YEARBLT,LOTAREA,STORIES,TOTALROOMS,GRADE,CONDITION,CDUDESC
0001C00167000000,POINT (1340992.9 411472.3),444 LIBERTY AVE 15222,NaN,444 LIBERTY AVE,444,NaN,NaN,LIBERTY AVE,PITTSBURGH,15222,...,NaT,NaN,NaN,<NA>,54582,NaN,<NA>,NaN,<NA>,NaN

In [3682]:
props_export.to_file('data/final/PropertyData_clean.shp.zip')

/var/folders/zj/02jlcxcn1dz5jm6ct_f_4wrr0000gn/T/ipykernel_37114/415732573.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  props_export.to_file('data/final/PropertyData_clean.shp.zip')